/**
 * List of protected app routes that should never be treated as custom domains
 * These routes are part of the application's core functionality
 */
export const PROTECTED_ROUTES: string[] = [
  'dashboard',
  'dashboard-backup',
  'stitch-dashboard',
  'auth',
  'profile',
  'family-creator',
  'family-builder',
  'family-builder-new',
  'family-builder-stitch',
  'family-tree-view',
  'family-statistics',
  'family-gallery',
  'family-suggestions',
  'payments',
  'plan-selection',
  'payment-success',
  'payment',
  'change-password',
  'store',
  'admin',
  'admin-api-settings',
  'renew-subscription',
  'terms-conditions',
  'privacy-policy',
  'contact',
  'tree',
  'share',
  'terms',
  '404',
  'api-docs',
  'stitch-tree-view',
  'stitch-account',
];
