-- Add translation keys for Dashboard, Family Builder, and Auth pages (Fixed)
INSERT INTO translations (key, value, language_code, category) VALUES

-- Dashboard translations - English
('dashboard_welcome', 'Welcome', 'en', 'dashboard'),
('no_trees', 'No trees yet', 'en', 'dashboard'), 
('trees', 'trees', 'en', 'dashboard'),
('no_trees_desc', 'Start your journey building your digital family legacy', 'en', 'dashboard'),
('dashboard_welcome_badge', 'Dashboard', 'en', 'dashboard'),
('online', 'Online', 'en', 'dashboard'),
('free_account', 'Free Account', 'en', 'dashboard'),
('upgrade_account', 'Upgrade Account', 'en', 'dashboard'),
('my_family_trees', 'My Family Trees', 'en', 'dashboard'),
('create_new_tree', 'Create New Tree', 'en', 'dashboard'),
('tree_actions', 'Tree Actions', 'en', 'dashboard'),
('view_tree', 'View Tree', 'en', 'dashboard'),
('edit_tree', 'Edit Tree', 'en', 'dashboard'),
('delete_tree', 'Delete Tree', 'en', 'dashboard'),
('created_on', 'Created on', 'en', 'dashboard'),
('members_count', 'members', 'en', 'dashboard'),
('upgrade_modal_title', 'Upgrade Required', 'en', 'dashboard'),
('upgrade_modal_desc', 'You have reached the maximum number of family trees for your current plan', 'en', 'dashboard'),
('view_plans', 'View Plans', 'en', 'dashboard'),
('delete_confirmation', 'Delete Confirmation', 'en', 'dashboard'),
('delete_tree_warning', 'To confirm deletion, please type the tree name exactly as shown', 'en', 'dashboard'),
('type_tree_name', 'Type tree name to confirm', 'en', 'dashboard'),
('confirm_delete', 'Confirm Delete', 'en', 'dashboard'),
('cancel', 'Cancel', 'en', 'dashboard'),
('data_loading_error', 'Error loading data', 'en', 'dashboard'),
('delete_confirmation_error', 'Confirmation Error', 'en', 'dashboard'),
('tree_name_validation', 'You must type the tree name correctly to confirm', 'en', 'dashboard'),
('delete_error', 'Delete Error', 'en', 'dashboard'),
('delete_success', 'Deleted Successfully', 'en', 'dashboard'),
('tree_deleted_success', 'Family tree has been deleted successfully', 'en', 'dashboard'),

-- Dashboard translations - Arabic
('dashboard_welcome', 'أهلاً', 'ar', 'dashboard'),
('no_trees', 'لا توجد أشجار بعد', 'ar', 'dashboard'),
('trees', 'أشجار', 'ar', 'dashboard'),
('no_trees_desc', 'ابدأ رحلتك في بناء إرثك العائلي الرقمي', 'ar', 'dashboard'),
('dashboard_welcome_badge', 'لوحة التحكم', 'ar', 'dashboard'),
('online', 'متصل', 'ar', 'dashboard'),
('free_account', 'حساب مجاني', 'ar', 'dashboard'),
('upgrade_account', 'طوّر حسابك', 'ar', 'dashboard'),
('my_family_trees', 'أشجار عائلتي', 'ar', 'dashboard'),
('create_new_tree', 'إنشاء شجرة جديدة', 'ar', 'dashboard'),
('tree_actions', 'إجراءات الشجرة', 'ar', 'dashboard'),
('view_tree', 'عرض الشجرة', 'ar', 'dashboard'),
('edit_tree', 'تعديل الشجرة', 'ar', 'dashboard'),
('delete_tree', 'حذف الشجرة', 'ar', 'dashboard'),
('created_on', 'تم الإنشاء في', 'ar', 'dashboard'),
('members_count', 'أعضاء', 'ar', 'dashboard'),
('upgrade_modal_title', 'يلزم ترقية الحساب', 'ar', 'dashboard'),
('upgrade_modal_desc', 'لقد وصلت للحد الأقصى من أشجار العائلة في باقتك الحالية', 'ar', 'dashboard'),
('view_plans', 'عرض الباقات', 'ar', 'dashboard'),
('delete_confirmation', 'تأكيد الحذف', 'ar', 'dashboard'),
('delete_tree_warning', 'لتأكيد الحذف، يرجى كتابة اسم الشجرة كما هو موضح تماماً', 'ar', 'dashboard'),
('type_tree_name', 'اكتب اسم الشجرة للتأكيد', 'ar', 'dashboard'),
('confirm_delete', 'تأكيد الحذف', 'ar', 'dashboard'),
('cancel', 'إلغاء', 'ar', 'dashboard'),
('data_loading_error', 'خطأ في تحميل البيانات', 'ar', 'dashboard'),
('delete_confirmation_error', 'خطأ في التأكيد', 'ar', 'dashboard'),
('tree_name_validation', 'يجب كتابة اسم الشجرة بشكل صحيح للتأكيد', 'ar', 'dashboard'),
('delete_error', 'خطأ في الحذف', 'ar', 'dashboard'),
('delete_success', 'تم الحذف بنجاح', 'ar', 'dashboard'),
('tree_deleted_success', 'تم حذف شجرة العائلة بنجاح', 'ar', 'dashboard')

ON CONFLICT (language_code, key) DO UPDATE SET
  value = EXCLUDED.value,
  category = EXCLUDED.category,
  updated_at = now();