-- Add Auth page translation keys
INSERT INTO translations (key, value, language_code, category) VALUES
-- Auth page translations - English
('welcome_to', 'Welcome to', 'en', 'auth'),
('my_tree', 'My Tree', 'en', 'auth'),
('exceptional_journey', 'Start your exceptional journey in discovering your roots and building a luxurious digital legacy', 'en', 'auth'),
('best_arabic_platform', 'with the best Arabic platform for creating family trees', 'en', 'auth'),
('distinguished_families', '+1000 Distinguished Families', 'en', 'auth'),
('preserved_individuals', '+50k Preserved Individuals', 'en', 'auth'),
('high_security', '100% High Security', 'en', 'auth'),
('luxury_design', 'Luxury Design', 'en', 'auth'),
('high_quality', 'High Quality', 'en', 'auth'),
('premium_experience', 'Premium Experience', 'en', 'auth'),
('discover_roots', 'Discover your roots with the best platform', 'en', 'auth'),
('join_my_tree', 'Join My Tree', 'en', 'auth'),
('start_exceptional_journey_building', 'Start your exceptional journey in building your digital family legacy', 'en', 'auth'),
('account_verification', 'Account Verification', 'en', 'auth'),
('enter_verification_code_sent_to', 'Enter the verification code sent to', 'en', 'auth'),
('verification_code', 'Verification Code', 'en', 'auth'),
('enter_6_digit_code', 'Enter the 6-digit code', 'en', 'auth'),
('verifying', 'Verifying...', 'en', 'auth'),
('verify_account', 'Verify Account', 'en', 'auth'),
('resend_code', 'Resend Code', 'en', 'auth'),
('back_to_register', 'Back to Registration', 'en', 'auth'),
('create_account', 'Create Account', 'en', 'auth'),
('sign_in', 'Sign In', 'en', 'auth'),
('full_name', 'Full Name', 'en', 'auth'),
('enter_full_name', 'Enter your full name', 'en', 'auth'),
('email_address', 'Email Address', 'en', 'auth'),
('phone_number', 'Phone Number', 'en', 'auth'),
('password', 'Password', 'en', 'auth'),
('enter_strong_password', 'Enter a strong password', 'en', 'auth'),
('creating_account', 'Creating account...', 'en', 'auth'),
('create_new_account', 'Create New Account', 'en', 'auth'),
('enter_password', 'Enter password', 'en', 'auth'),
('forgot_password', 'Forgot password?', 'en', 'auth'),
('signing_in', 'Signing in...', 'en', 'auth'),
('or', 'or', 'en', 'auth'),
('continue_with_google', 'Continue with Google', 'en', 'auth'),
('back_to_home', 'Back to Home Page', 'en', 'auth'),

-- Auth page translations - Arabic
('welcome_to', 'مرحباً بك في', 'ar', 'auth'),
('my_tree', 'شجرتي', 'ar', 'auth'),
('exceptional_journey', 'ابدأ رحلتك الاستثنائية في اكتشاف جذورك وبناء إرث رقمي فاخر', 'ar', 'auth'),
('best_arabic_platform', 'مع أفضل منصة عربية لإنشاء أشجار العائلة', 'ar', 'auth'),
('distinguished_families', '+1000 عائلة مميزة', 'ar', 'auth'),
('preserved_individuals', '+50k فرد محفوظ', 'ar', 'auth'),
('high_security', '100% آمان عالي', 'ar', 'auth'),
('luxury_design', 'تصميم فاخر', 'ar', 'auth'),
('high_quality', 'جودة عالية', 'ar', 'auth'),
('premium_experience', 'تجربة مميزة', 'ar', 'auth'),
('discover_roots', 'اكتشف جذورك مع أفضل منصة', 'ar', 'auth'),
('join_my_tree', 'انضم إلى شجرتي', 'ar', 'auth'),
('start_exceptional_journey_building', 'ابدأ رحلتك الاستثنائية في بناء إرث عائلتك الرقمي', 'ar', 'auth'),
('account_verification', 'تأكيد الحساب', 'ar', 'auth'),
('enter_verification_code_sent_to', 'أدخل رمز التحقق المرسل إلى', 'ar', 'auth'),
('verification_code', 'رمز التحقق', 'ar', 'auth'),
('enter_6_digit_code', 'أدخل الرمز المكون من 6 أرقام', 'ar', 'auth'),
('verifying', 'جاري التحقق...', 'ar', 'auth'),
('verify_account', 'تأكيد الحساب', 'ar', 'auth'),
('resend_code', 'إعادة إرسال الرمز', 'ar', 'auth'),
('back_to_register', 'العودة إلى إنشاء الحساب', 'ar', 'auth'),
('create_account', 'إنشاء حساب', 'ar', 'auth'),
('sign_in', 'تسجيل الدخول', 'ar', 'auth'),
('full_name', 'الاسم الكامل', 'ar', 'auth'),
('enter_full_name', 'أدخل اسمك الكامل', 'ar', 'auth'),
('email_address', 'البريد الإلكتروني', 'ar', 'auth'),
('phone_number', 'رقم الهاتف', 'ar', 'auth'),
('password', 'كلمة المرور', 'ar', 'auth'),
('enter_strong_password', 'أدخل كلمة مرور قوية', 'ar', 'auth'),
('creating_account', 'جاري إنشاء الحساب...', 'ar', 'auth'),
('create_new_account', 'إنشاء حساب جديد', 'ar', 'auth'),
('enter_password', 'أدخل كلمة المرور', 'ar', 'auth'),
('forgot_password', 'نسيت كلمة المرور؟', 'ar', 'auth'),
('signing_in', 'جاري تسجيل الدخول...', 'ar', 'auth'),
('or', 'أو', 'ar', 'auth'),
('continue_with_google', 'متابعة مع Google', 'ar', 'auth'),
('back_to_home', 'العودة إلى الصفحة الرئيسية', 'ar', 'auth')

ON CONFLICT (language_code, key) DO UPDATE SET
  value = EXCLUDED.value,
  category = EXCLUDED.category,
  updated_at = now();