-- Add comprehensive FamilyBuilder translation keys
INSERT INTO public.translations (language_code, key, value, category) VALUES
-- Arabic translations for FamilyBuilder
('ar', 'family_builder.family', 'عائلة', 'family'),
('ar', 'family_builder.loading', 'جاري تحميل بيانات العائلة...', 'family'),
('ar', 'family_builder.error_loading', 'حدث خطأ أثناء تحميل بيانات العائلة', 'family'),
('ar', 'family_builder.unspecified', 'غير محدد', 'family'),
('ar', 'family_builder.last_modified', 'آخر تعديل', 'family'),
('ar', 'family_builder.statistics', 'الإحصائات', 'family'),
('ar', 'family_builder.search_placeholder', 'البحث في أفراد العائلة...', 'family'),
('ar', 'family_builder.add_member', 'إضافة فرد', 'family'),
('ar', 'family_builder.male', 'ذكر', 'family'),
('ar', 'family_builder.female', 'أنثى', 'family'),
('ar', 'family_builder.edit_data', 'تعديل البيانات', 'family'),
('ar', 'family_builder.delete_from_family', 'حذف من العائلة', 'family'),
('ar', 'family_builder.alive', 'على قيد الحياة', 'family'),
('ar', 'family_builder.deceased', 'متوفى', 'family'),
('ar', 'family_builder.add_new_member', 'إضافة فرد جديد', 'family'),
('ar', 'family_builder.click_to_add', 'انقر هنا لإضافة عضو جديد إلى شجرة العائلة', 'family'),
('ar', 'family_builder.family_tree', 'شجرة العائلة', 'family'),
('ar', 'family_builder.interactive_view', 'عرض تفاعلي لشجرة العائلة', 'family'),
('ar', 'family_builder.coming_soon', 'سيتم إضافة عرض تفاعلي للشجرة قريباً', 'family'),
('ar', 'family_builder.edit_member', 'تعديل بيانات العضو', 'family'),
('ar', 'family_builder.edit_info', 'قم بتعديل معلومات العضو', 'family'),
('ar', 'family_builder.add_info', 'أدخل معلومات الفرد الجديد', 'family'),
('ar', 'family_builder.choose_family', 'اختر العائلة المرتبطة', 'family'),
('ar', 'family_builder.search_family', 'ابحث عن عائلة...', 'family'),
('ar', 'family_builder.selected_family_not_found', 'العائلة المحددة غير موجودة', 'family'),
('ar', 'family_builder.saved_image', 'تم حفظ الصورة', 'family'),
('ar', 'family_builder.image_saved_desc', 'تم قص الصورة وحفظها بنجاح', 'family'),

-- English translations for FamilyBuilder
('en', 'family_builder.family', 'Family', 'family'),
('en', 'family_builder.loading', 'Loading family data...', 'family'),
('en', 'family_builder.error_loading', 'Error loading family data', 'family'),
('en', 'family_builder.unspecified', 'Unspecified', 'family'),
('en', 'family_builder.last_modified', 'Last Modified', 'family'),
('en', 'family_builder.statistics', 'Statistics', 'family'),
('en', 'family_builder.search_placeholder', 'Search family members...', 'family'),
('en', 'family_builder.add_member', 'Add Member', 'family'),
('en', 'family_builder.male', 'Male', 'family'),
('en', 'family_builder.female', 'Female', 'family'),
('en', 'family_builder.edit_data', 'Edit Data', 'family'),
('en', 'family_builder.delete_from_family', 'Delete from Family', 'family'),
('en', 'family_builder.alive', 'Alive', 'family'),
('en', 'family_builder.deceased', 'Deceased', 'family'),
('en', 'family_builder.add_new_member', 'Add New Member', 'family'),
('en', 'family_builder.click_to_add', 'Click here to add a new member to the family tree', 'family'),
('en', 'family_builder.family_tree', 'Family Tree', 'family'),
('en', 'family_builder.interactive_view', 'Interactive family tree view', 'family'),
('en', 'family_builder.coming_soon', 'Interactive tree view will be added soon', 'family'),
('en', 'family_builder.edit_member', 'Edit Member Data', 'family'),
('en', 'family_builder.edit_info', 'Edit member information', 'family'),
('en', 'family_builder.add_info', 'Enter new member information', 'family'),
('en', 'family_builder.choose_family', 'Choose Related Family', 'family'),
('en', 'family_builder.search_family', 'Search for family...', 'family'),
('en', 'family_builder.selected_family_not_found', 'Selected family not found', 'family'),
('en', 'family_builder.saved_image', 'Image Saved', 'family'),
('en', 'family_builder.image_saved_desc', 'Image cropped and saved successfully', 'family')
ON CONFLICT (language_code, key) DO NOTHING;