-- Add additional missing Auth page translation keys for better coverage
INSERT INTO public.translations (language_code, key, value, category) VALUES
-- Missing Arabic translations for Auth page error/success messages
('ar', 'error', 'خطأ', 'auth'),
('ar', 'login_error_general', 'حدث خطأ أثناء تسجيل الدخول', 'auth'),
('ar', 'register_error', 'خطأ في إنشاء الحساب', 'auth'),
('ar', 'register_error_general', 'حدث خطأ أثناء إنشاء الحساب', 'auth'),
('ar', 'verification_error', 'خطأ في التحقق', 'auth'),
('ar', 'verification_error_general', 'حدث خطأ أثناء التحقق', 'auth'),
('ar', 'verification_successful', 'تم التحقق بنجاح', 'auth'),
('ar', 'welcome_to_my_tree', 'مرحباً بك في شجرتي', 'auth'),
('ar', 'resend_error', 'خطأ في إعادة الإرسال', 'auth'),
('ar', 'resend_error_general', 'حدث خطأ أثناء إعادة الإرسال', 'auth'),
('ar', 'resent_successfully', 'تم إعادة الإرسال', 'auth'),
('ar', 'resent_description', 'تم إرسال رمز تحقق جديد إلى بريدك الإلكتروني', 'auth'),
('ar', 'google_login_error', 'حدث خطأ أثناء تسجيل الدخول بـ Google', 'auth'),

-- English translations
('en', 'email_not_confirmed', 'Email not confirmed', 'auth'),
('en', 'will_send_verification_code', 'We will send you a new verification code', 'auth'),
('en', 'sending_error', 'Sending error', 'auth'),
('en', 'verification_code_sent', 'Verification code sent', 'auth'),
('en', 'enter_code_instruction', 'Please enter the code sent to your email', 'auth'),
('en', 'login_error', 'Login error', 'auth'),
('en', 'welcome', 'Welcome', 'auth'),
('en', 'login_successful', 'Login successful', 'auth'),
('en', 'error', 'Error', 'auth'),
('en', 'login_error_general', 'An error occurred during login', 'auth'),
('en', 'register_error', 'Account creation error', 'auth'),
('en', 'register_error_general', 'An error occurred during account creation', 'auth'),
('en', 'verification_error', 'Verification error', 'auth'),
('en', 'verification_error_general', 'An error occurred during verification', 'auth'),
('en', 'verification_successful', 'Verification successful', 'auth'),
('en', 'welcome_to_my_tree', 'Welcome to My Tree', 'auth'),
('en', 'resend_error', 'Resend error', 'auth'),
('en', 'resend_error_general', 'An error occurred during resend', 'auth'),
('en', 'resent_successfully', 'Resent successfully', 'auth'),
('en', 'resent_description', 'A new verification code has been sent to your email', 'auth'),
('en', 'google_login_error', 'An error occurred during Google login', 'auth');