-- Add comprehensive batch of missing FamilyBuilder translation keys

INSERT INTO translations (language_code, key, value, category) VALUES

-- Missing Arabic translations for hardcoded text in FamilyBuilder
('ar', 'family_builder.generations', 'أجيال', 'family'),
('ar', 'family_builder.members_count', 'أعضاء', 'family'),
('ar', 'family_builder.today', 'اليوم', 'family'),
('ar', 'family_builder.overview', 'نظرة عامة', 'family'),
('ar', 'family_builder.tree_diagram', 'مخطط الشجرة', 'family'),
('ar', 'family_builder.store', 'المتجر', 'family'),
('ar', 'family_builder.max_reached', 'وصلت للحد الأقصى', 'family'),
('ar', 'family_builder.born', 'مولود', 'family'),
('ar', 'family_builder.died', 'توفي', 'family'),
('ar', 'family_builder.age', 'العمر', 'family'),
('ar', 'family_builder.years', 'سنة', 'family'),
('ar', 'family_builder.edit', 'تعديل', 'family'),
('ar', 'family_builder.delete', 'حذف', 'family'),
('ar', 'family_builder.no_members_found', 'لا توجد نتائج للبحث', 'family'),
('ar', 'family_builder.start_building', 'ابدأ ببناء شجرة العائلة', 'family'),
('ar', 'family_builder.add_first_member', 'أضف العضو الأول لبدء بناء شجرة العائلة الخاصة بك', 'family'),
('ar', 'family_builder.add_first_member_button', 'إضافة العضو الأول', 'family'),
('ar', 'family_builder.children', 'الأطفال', 'family'),
('ar', 'family_builder.no_children', 'لا يوجد أطفال', 'family'),
('ar', 'family_builder.add_child', 'إضافة طفل', 'family'),
('ar', 'family_builder.marriages', 'الزيجات', 'family'),
('ar', 'family_builder.add_marriage', 'إضافة زواج', 'family'),
('ar', 'family_builder.husband', 'الزوج', 'family'),
('ar', 'family_builder.wife', 'الزوجة', 'family'),
('ar', 'family_builder.birth_year', 'سنة الميلاد', 'family'),
('ar', 'family_builder.death_year', 'سنة الوفاة', 'family'),
('ar', 'family_builder.biography', 'السيرة الذاتية', 'family'),
('ar', 'family_builder.upload_image', 'رفع صورة', 'family'),
('ar', 'family_builder.save', 'حفظ', 'family'),
('ar', 'family_builder.cancel', 'إلغاء', 'family'),
('ar', 'family_builder.name', 'الاسم', 'family'),
('ar', 'family_builder.gender', 'الجنس', 'family'),
('ar', 'family_builder.required', 'مطلوب', 'family'),
('ar', 'family_builder.optional', 'اختياري', 'family'),
('ar', 'family_builder.crop_image', 'قص الصورة', 'family'),
('ar', 'family_builder.image_preview', 'معاينة الصورة', 'family'),
('ar', 'family_builder.select_image', 'اختر صورة', 'family'),
('ar', 'family_builder.confirm_delete', 'تأكيد الحذف', 'family'),
('ar', 'family_builder.delete_warning', 'هل أنت متأكد من حذف هذا العضو؟', 'family'),
('ar', 'family_builder.cannot_undo', 'هذا الإجراء لا يمكن التراجع عنه', 'family'),
('ar', 'family_builder.close', 'إغلاق', 'family'),
('ar', 'family_builder.next', 'التالي', 'family'),
('ar', 'family_builder.previous', 'السابق', 'family'),
('ar', 'family_builder.step', 'خطوة', 'family'),
('ar', 'family_builder.of', 'من', 'family'),
('ar', 'family_builder.finish', 'إنهاء', 'family'),
('ar', 'family_builder.basic_info', 'المعلومات الأساسية', 'family'),
('ar', 'family_builder.additional_info', 'معلومات إضافية', 'family'),
('ar', 'family_builder.relationship', 'العلاقة', 'family'),
('ar', 'family_builder.select_gender', 'اختر الجنس', 'family'),
('ar', 'family_builder.select_relationship', 'اختر العلاقة', 'family'),
('ar', 'family_builder.family_name', 'اسم العائلة', 'family'),

-- Missing English translations
('en', 'family_builder.generations', 'Generations', 'family'),
('en', 'family_builder.members_count', 'Members', 'family'),
('en', 'family_builder.today', 'Today', 'family'),
('en', 'family_builder.overview', 'Overview', 'family'),
('en', 'family_builder.tree_diagram', 'Tree Diagram', 'family'),
('en', 'family_builder.store', 'Store', 'family'),
('en', 'family_builder.max_reached', 'Max Reached', 'family'),
('en', 'family_builder.born', 'Born', 'family'),
('en', 'family_builder.died', 'Died', 'family'),
('en', 'family_builder.age', 'Age', 'family'),
('en', 'family_builder.years', 'years', 'family'),
('en', 'family_builder.edit', 'Edit', 'family'),
('en', 'family_builder.delete', 'Delete', 'family'),
('en', 'family_builder.no_members_found', 'No search results found', 'family'),
('en', 'family_builder.start_building', 'Start Building Family Tree', 'family'),
('en', 'family_builder.add_first_member', 'Add the first member to start building your family tree', 'family'),
('en', 'family_builder.add_first_member_button', 'Add First Member', 'family'),
('en', 'family_builder.children', 'Children', 'family'),
('en', 'family_builder.no_children', 'No children', 'family'),
('en', 'family_builder.add_child', 'Add Child', 'family'),
('en', 'family_builder.marriages', 'Marriages', 'family'),
('en', 'family_builder.add_marriage', 'Add Marriage', 'family'),
('en', 'family_builder.husband', 'Husband', 'family'),
('en', 'family_builder.wife', 'Wife', 'family'),
('en', 'family_builder.birth_year', 'Birth Year', 'family'),
('en', 'family_builder.death_year', 'Death Year', 'family'),
('en', 'family_builder.biography', 'Biography', 'family'),
('en', 'family_builder.upload_image', 'Upload Image', 'family'),
('en', 'family_builder.save', 'Save', 'family'),
('en', 'family_builder.cancel', 'Cancel', 'family'),
('en', 'family_builder.name', 'Name', 'family'),
('en', 'family_builder.gender', 'Gender', 'family'),
('en', 'family_builder.required', 'Required', 'family'),
('en', 'family_builder.optional', 'Optional', 'family'),
('en', 'family_builder.crop_image', 'Crop Image', 'family'),
('en', 'family_builder.image_preview', 'Image Preview', 'family'),
('en', 'family_builder.select_image', 'Select Image', 'family'),
('en', 'family_builder.confirm_delete', 'Confirm Delete', 'family'),
('en', 'family_builder.delete_warning', 'Are you sure you want to delete this member?', 'family'),
('en', 'family_builder.cannot_undo', 'This action cannot be undone', 'family'),
('en', 'family_builder.close', 'Close', 'family'),
('en', 'family_builder.next', 'Next', 'family'),
('en', 'family_builder.previous', 'Previous', 'family'),
('en', 'family_builder.step', 'Step', 'family'),
('en', 'family_builder.of', 'of', 'family'),
('en', 'family_builder.finish', 'Finish', 'family'),
('en', 'family_builder.basic_info', 'Basic Information', 'family'),
('en', 'family_builder.additional_info', 'Additional Information', 'family'),
('en', 'family_builder.relationship', 'Relationship', 'family'),
('en', 'family_builder.select_gender', 'Select Gender', 'family'),
('en', 'family_builder.select_relationship', 'Select Relationship', 'family'),
('en', 'family_builder.family_name', 'Family Name', 'family')

ON CONFLICT (language_code, key) DO UPDATE SET value = EXCLUDED.value;