-- Insert GlobalHeader translation keys for English and Arabic
INSERT INTO translations (key, value, language_code, category) VALUES
-- GlobalHeader translations - English
('site.name', 'Family Tree', 'en', 'header'),
('nav.admin', 'Admin Panel', 'en', 'header'),
('nav.dashboard', 'Dashboard', 'en', 'header'),
('nav.dashboard.desc', 'Manage Family Tree', 'en', 'header'),
('nav.contact', 'Contact Us', 'en', 'header'),
('nav.settings', 'Settings', 'en', 'header'),
('nav.settings.desc', 'Customize Account', 'en', 'header'),
('nav.billing', 'Billing', 'en', 'header'),
('nav.billing.desc', 'Manage Subscriptions', 'en', 'header'),
('nav.help', 'Help', 'en', 'header'),
('nav.help.desc', 'Support & Guidance', 'en', 'header'),
('nav.logout', 'Sign Out', 'en', 'header'),
('nav.logout.desc', 'End Session', 'en', 'header'),
('nav.login', 'Sign In', 'en', 'header'),
('nav.pricing', 'Pricing', 'en', 'header'),
('language.name', 'Language', 'en', 'header'),

-- GlobalHeader translations - Arabic
('site.name', 'شجرة العائلة', 'ar', 'header'),
('nav.admin', 'لوحة الإدارة', 'ar', 'header'),
('nav.dashboard', 'لوحة التحكم', 'ar', 'header'),
('nav.dashboard.desc', 'إدارة شجرة العائلة', 'ar', 'header'),
('nav.contact', 'تواصل معنا', 'ar', 'header'),
('nav.settings', 'الإعدادات', 'ar', 'header'),
('nav.settings.desc', 'تخصيص الحساب', 'ar', 'header'),
('nav.billing', 'الفواتير', 'ar', 'header'),
('nav.billing.desc', 'إدارة الاشتراكات', 'ar', 'header'),
('nav.help', 'المساعدة', 'ar', 'header'),
('nav.help.desc', 'الدعم والتوجيه', 'ar', 'header'),
('nav.logout', 'تسجيل الخروج', 'ar', 'header'),
('nav.logout.desc', 'إنهاء الجلسة', 'ar', 'header'),
('nav.login', 'تسجيل الدخول', 'ar', 'header'),
('nav.pricing', 'الأسعار', 'ar', 'header'),
('language.name', 'اللغة', 'ar', 'header'),

-- GlobalFooter translations - English
('footer_brand_name', 'Family Tree', 'en', 'footer'),
('footer_brand_description', 'We preserve your heritage and build your digital legacy for future generations with the latest technology and highest quality standards', 'en', 'footer'),
('footer_brand_badge', 'Best in the Region', 'en', 'footer'),
('footer_quick_links_title', 'Quick Links', 'en', 'footer'),
('footer_link_home', 'Home', 'en', 'footer'),
('footer_link_dashboard', 'Dashboard', 'en', 'footer'),
('footer_link_auth', 'Sign In', 'en', 'footer'),
('footer_support_title', 'Support & Help', 'en', 'footer'),
('footer_link_terms', 'Terms & Conditions', 'en', 'footer'),
('footer_link_help', 'Help Center', 'en', 'footer'),
('footer_link_contact', 'Contact Us', 'en', 'footer'),
('footer_contact_title', 'Contact Us', 'en', 'footer'),
('footer_trust_data', 'Certified Data Protection', 'en', 'footer'),
('footer_trust_rating', '5-Star Customer Rating', 'en', 'footer'),
('footer_copyright', '© 2024 Family Tree. All rights reserved.', 'en', 'footer'),
('footer_made_with_love', 'Made with love in the Middle East', 'en', 'footer'),

-- GlobalFooter translations - Arabic
('footer_brand_name', 'شجرة العائلة', 'ar', 'footer'),
('footer_brand_description', 'نحفظ تراثك ونبني إرثك الرقمي للأجيال القادمة بأحدث التقنيات وأعلى معايير الجودة', 'ar', 'footer'),
('footer_brand_badge', 'الأفضل في المنطقة', 'ar', 'footer'),
('footer_quick_links_title', 'روابط سريعة', 'ar', 'footer'),
('footer_link_home', 'الرئيسية', 'ar', 'footer'),
('footer_link_dashboard', 'لوحة التحكم', 'ar', 'footer'),
('footer_link_auth', 'تسجيل الدخول', 'ar', 'footer'),
('footer_support_title', 'الدعم والمساعدة', 'ar', 'footer'),
('footer_link_terms', 'الشروط والأحكام', 'ar', 'footer'),
('footer_link_help', 'مركز المساعدة', 'ar', 'footer'),
('footer_link_contact', 'تواصل معنا', 'ar', 'footer'),
('footer_contact_title', 'تواصل معنا', 'ar', 'footer'),
('footer_trust_data', 'حماية البيانات معتمدة', 'ar', 'footer'),
('footer_trust_rating', 'تقييم ٥ نجوم من العملاء', 'ar', 'footer'),
('footer_copyright', '© ٢٠٢٤ شجرة العائلة. جميع الحقوق محفوظة.', 'ar', 'footer'),
('footer_made_with_love', 'صنع بحب في الشرق الأوسط', 'ar', 'footer')

ON CONFLICT (language_code, key) DO UPDATE SET
  value = EXCLUDED.value,
  category = EXCLUDED.category,
  updated_at = now();