-- Add page title translations for Arabic
INSERT INTO translations (language_code, key, value, category) VALUES
('ar', 'page_title_home', 'شجرتي - ابني شجرة عائلتك', 'page_titles'),
('ar', 'page_title_dashboard', 'شجرتي - لوحة التحكم', 'page_titles'),
('ar', 'page_title_profile', 'شجرتي - الملف الشخصي', 'page_titles'),
('ar', 'page_title_family_creator', 'شجرتي - إنشاء عائلة جديدة', 'page_titles'),
('ar', 'page_title_family_builder', 'شجرتي - بناء الشجرة', 'page_titles'),
('ar', 'page_title_family_tree_view', 'شجرتي - عرض الشجرة', 'page_titles'),
('ar', 'page_title_family_statistics', 'شجرتي - إحصائيات العائلة', 'page_titles'),
('ar', 'page_title_family_gallery', 'شجرتي - معرض الصور', 'page_titles'),
('ar', 'page_title_admin_panel', 'شجرتي - لوحة الإدارة', 'page_titles'),
('ar', 'page_title_admin_billing', 'شجرتي - الفواتير', 'page_titles'),
('ar', 'page_title_admin_email', 'شجرتي - البريد الإلكتروني', 'page_titles'),
('ar', 'page_title_admin_analytics', 'شجرتي - التحليلات', 'page_titles'),
('ar', 'page_title_payments', 'شجرتي - المدفوعات', 'page_titles'),
('ar', 'page_title_payment_success', 'شجرتي - نجاح الدفع', 'page_titles'),
('ar', 'page_title_renew_subscription', 'شجرتي - تجديد الاشتراك', 'page_titles'),
('ar', 'page_title_plan_selection', 'شجرتي - اختيار الباقة', 'page_titles'),
('ar', 'page_title_terms', 'شجرتي - الشروط والأحكام', 'page_titles'),
('ar', 'page_title_privacy', 'شجرتي - سياسة الخصوصية', 'page_titles'),
('ar', 'page_title_contact', 'شجرتي - اتصل بنا', 'page_titles'),
('ar', 'page_title_store', 'شجرتي - المتجر', 'page_titles'),
('ar', 'page_title_auth', 'شجرتي - تسجيل الدخول', 'page_titles'),
('ar', 'page_title_change_password', 'شجرتي - تغيير كلمة المرور', 'page_titles'),
('ar', 'page_title_public_tree', 'شجرتي - شجرة العائلة', 'page_titles'),
('ar', 'page_title_not_found', 'شجرتي - الصفحة غير موجودة', 'page_titles')
ON CONFLICT (language_code, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

-- Add page title translations for English
INSERT INTO translations (language_code, key, value, category) VALUES
('en', 'page_title_home', 'My Family Tree - Build Your Legacy', 'page_titles'),
('en', 'page_title_dashboard', 'My Family Tree - Dashboard', 'page_titles'),
('en', 'page_title_profile', 'My Family Tree - Profile', 'page_titles'),
('en', 'page_title_family_creator', 'My Family Tree - Create Family', 'page_titles'),
('en', 'page_title_family_builder', 'My Family Tree - Build Tree', 'page_titles'),
('en', 'page_title_family_tree_view', 'My Family Tree - Tree View', 'page_titles'),
('en', 'page_title_family_statistics', 'My Family Tree - Statistics', 'page_titles'),
('en', 'page_title_family_gallery', 'My Family Tree - Gallery', 'page_titles'),
('en', 'page_title_admin_panel', 'My Family Tree - Admin Panel', 'page_titles'),
('en', 'page_title_admin_billing', 'My Family Tree - Billing', 'page_titles'),
('en', 'page_title_admin_email', 'My Family Tree - Email Management', 'page_titles'),
('en', 'page_title_admin_analytics', 'My Family Tree - Analytics', 'page_titles'),
('en', 'page_title_payments', 'My Family Tree - Payments', 'page_titles'),
('en', 'page_title_payment_success', 'My Family Tree - Payment Success', 'page_titles'),
('en', 'page_title_renew_subscription', 'My Family Tree - Renew Subscription', 'page_titles'),
('en', 'page_title_plan_selection', 'My Family Tree - Select Plan', 'page_titles'),
('en', 'page_title_terms', 'My Family Tree - Terms & Conditions', 'page_titles'),
('en', 'page_title_privacy', 'My Family Tree - Privacy Policy', 'page_titles'),
('en', 'page_title_contact', 'My Family Tree - Contact Us', 'page_titles'),
('en', 'page_title_store', 'My Family Tree - Store', 'page_titles'),
('en', 'page_title_auth', 'My Family Tree - Sign In', 'page_titles'),
('en', 'page_title_change_password', 'My Family Tree - Change Password', 'page_titles'),
('en', 'page_title_public_tree', 'My Family Tree - Family Tree', 'page_titles'),
('en', 'page_title_not_found', 'My Family Tree - Page Not Found', 'page_titles')
ON CONFLICT (language_code, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
