-- Add remaining Auth page translation keys for form elements and UI text
INSERT INTO public.translations (language_code, key, value, category) VALUES
-- Arabic translations for Auth page UI elements
('ar', 'discover_roots_platform', 'اكتشف جذورك مع أفضل منصة', 'auth'),
('ar', 'join_my_tree', 'انضم إلى شجرتي', 'auth'),
('ar', 'start_exceptional_journey', 'ابدأ رحلتك الاستثنائية في بناء إرث عائلتك الرقمي', 'auth'),
('ar', 'account_confirmation', 'تأكيد الحساب', 'auth'),
('ar', 'enter_verification_code', 'أدخل رمز التحقق المرسل إلى', 'auth'),
('ar', 'verification_code', 'رمز التحقق', 'auth'),
('ar', 'enter_6_digit_code', 'أدخل الرمز المكون من 6 أرقام', 'auth'),
('ar', 'verifying', 'جاري التحقق...', 'auth'),
('ar', 'confirm_account', 'تأكيد الحساب', 'auth'),
('ar', 'resend_code', 'إعادة إرسال الرمز', 'auth'),
('ar', 'back_to_register', 'العودة إلى إنشاء الحساب', 'auth'),
('ar', 'create_account', 'إنشاء حساب', 'auth'),
('ar', 'login', 'تسجيل الدخول', 'auth'),
('ar', 'full_name', 'الاسم الكامل', 'auth'),
('ar', 'enter_full_name', 'أدخل اسمك الكامل', 'auth'),
('ar', 'email', 'البريد الإلكتروني', 'auth'),
('ar', 'phone_number', 'رقم الهاتف', 'auth'),
('ar', 'password', 'كلمة المرور', 'auth'),
('ar', 'enter_strong_password', 'أدخل كلمة مرور قوية', 'auth'),
('ar', 'creating_account', 'جاري إنشاء الحساب...', 'auth'),
('ar', 'create_new_account', 'إنشاء حساب جديد', 'auth'),
('ar', 'enter_password', 'أدخل كلمة المرور', 'auth'),
('ar', 'forgot_password', 'نسيت كلمة المرور؟', 'auth'),
('ar', 'logging_in', 'جاري تسجيل الدخول...', 'auth'),
('ar', 'or', 'أو', 'auth'),
('ar', 'continue_with_google', 'متابعة مع Google', 'auth'),
('ar', 'back_to_home', 'العودة إلى الصفحة الرئيسية', 'auth'),
('ar', 'distinguished_family', 'عائلة مميزة', 'auth'),
('ar', 'preserved_member', 'فرد محفوظ', 'auth'),
('ar', 'high_security', 'آمان عالي', 'auth'),
('ar', 'luxury_design', 'تصميم فاخر', 'auth'),
('ar', 'high_quality', 'جودة عالية', 'auth'),
('ar', 'distinctive_experience', 'تجربة مميزة', 'auth'),

-- English translations
('en', 'discover_roots_platform', 'Discover your roots with the best platform', 'auth'),
('en', 'join_my_tree', 'Join My Tree', 'auth'),
('en', 'start_exceptional_journey', 'Start your exceptional journey in building your family digital legacy', 'auth'),
('en', 'account_confirmation', 'Account Confirmation', 'auth'),
('en', 'enter_verification_code', 'Enter the verification code sent to', 'auth'),
('en', 'verification_code', 'Verification Code', 'auth'),
('en', 'enter_6_digit_code', 'Enter the 6-digit code', 'auth'),
('en', 'verifying', 'Verifying...', 'auth'),
('en', 'confirm_account', 'Confirm Account', 'auth'),
('en', 'resend_code', 'Resend Code', 'auth'),
('en', 'back_to_register', 'Back to Register', 'auth'),
('en', 'create_account', 'Create Account', 'auth'),
('en', 'login', 'Login', 'auth'),
('en', 'full_name', 'Full Name', 'auth'),
('en', 'enter_full_name', 'Enter your full name', 'auth'),
('en', 'email', 'Email', 'auth'),
('en', 'phone_number', 'Phone Number', 'auth'),
('en', 'password', 'Password', 'auth'),
('en', 'enter_strong_password', 'Enter a strong password', 'auth'),
('en', 'creating_account', 'Creating account...', 'auth'),
('en', 'create_new_account', 'Create New Account', 'auth'),
('en', 'enter_password', 'Enter password', 'auth'),
('en', 'forgot_password', 'Forgot password?', 'auth'),
('en', 'logging_in', 'Logging in...', 'auth'),
('en', 'or', 'Or', 'auth'),
('en', 'continue_with_google', 'Continue with Google', 'auth'),
('en', 'back_to_home', 'Back to Home', 'auth'),
('en', 'distinguished_family', 'Distinguished Family', 'auth'),
('en', 'preserved_member', 'Preserved Member', 'auth'),
('en', 'high_security', 'High Security', 'auth'),
('en', 'luxury_design', 'Luxury Design', 'auth'),
('en', 'high_quality', 'High Quality', 'auth'),
('en', 'distinctive_experience', 'Distinctive Experience', 'auth');