-- Insert missing translation keys for Tree Settings sharing and domain section

INSERT INTO public.translations (key, language_code, category, value) VALUES
-- Sharing & Domain Settings Card
('tree_settings.sharing_domain_title', 'ar', 'tree_settings', 'إعدادات المشاركة والنطاق'),
('tree_settings.sharing_domain_title', 'en', 'tree_settings', 'Sharing & Domain Settings'),
('tree_settings.sharing_domain_desc', 'ar', 'tree_settings', 'تحكم في كيفية مشاركة شجرة العائلة ونطاقها المخصص'),
('tree_settings.sharing_domain_desc', 'en', 'tree_settings', 'Control how your family tree is shared and its custom domain'),

-- Public Share Link Section
('tree_settings.public_link_title', 'ar', 'tree_settings', 'الرابط العام للشجرة'),
('tree_settings.public_link_title', 'en', 'tree_settings', 'Public Tree Link'),
('tree_settings.generate_new_link', 'ar', 'tree_settings', 'توليد رابط جديد'),
('tree_settings.generate_new_link', 'en', 'tree_settings', 'Generate New Link'),
('tree_settings.share_button', 'ar', 'tree_settings', 'مشاركة'),
('tree_settings.share_button', 'en', 'tree_settings', 'Share'),
('tree_settings.expires_at', 'ar', 'tree_settings', 'ينتهي في:'),
('tree_settings.expires_at', 'en', 'tree_settings', 'Expires at:'),
('tree_settings.public_link_desc', 'ar', 'tree_settings', 'يمكن لأي شخص عرض الشجرة باستخدام هذا الرابط (صالح لمدة ساعتين)'),
('tree_settings.public_link_desc', 'en', 'tree_settings', 'Anyone can view the tree using this link (valid for 2 hours)'),

-- Custom Domain Section
('tree_settings.custom_link_title', 'ar', 'tree_settings', 'الرابط المخصص'),
('tree_settings.custom_link_title', 'en', 'tree_settings', 'Custom Link'),
('tree_settings.custom_link_premium_desc', 'ar', 'tree_settings', 'احصل على رابط مخصص سهل التذكر لشجرتك'),
('tree_settings.custom_link_premium_desc', 'en', 'tree_settings', 'Get an easy-to-remember custom link for your tree'),
('tree_settings.upgrade_now', 'ar', 'tree_settings', 'ترقية الآن'),
('tree_settings.upgrade_now', 'en', 'tree_settings', 'Upgrade Now'),
('tree_settings.available_badge', 'ar', 'tree_settings', 'متاح'),
('tree_settings.available_badge', 'en', 'tree_settings', 'Available'),
('tree_settings.add_custom_link', 'ar', 'tree_settings', 'إضافة رابط مخصص لشجرتك'),
('tree_settings.add_custom_link', 'en', 'tree_settings', 'Add custom link to your tree'),
('tree_settings.custom_link_example', 'ar', 'tree_settings', 'اختر رابطاً سهلاً مثل: https://shjrti.com/my-family'),
('tree_settings.custom_link_example', 'en', 'tree_settings', 'Choose an easy link like: https://shjrti.com/my-family'),
('tree_settings.copy_button', 'ar', 'tree_settings', 'نسخ'),
('tree_settings.copy_button', 'en', 'tree_settings', 'Copy'),
('tree_settings.edit_button', 'ar', 'tree_settings', 'تعديل'),
('tree_settings.edit_button', 'en', 'tree_settings', 'Edit'),

-- Gallery Sharing Section
('tree_settings.gallery_sharing_title', 'ar', 'tree_settings', 'مشاركة ألبوم صور العائلة'),
('tree_settings.gallery_sharing_title', 'en', 'tree_settings', 'Share Family Photo Album'),
('tree_settings.gallery_sharing_premium', 'ar', 'tree_settings', 'مشاركة ألبوم الصور'),
('tree_settings.gallery_sharing_premium', 'en', 'tree_settings', 'Share Photo Album'),
('tree_settings.gallery_sharing_premium_desc', 'ar', 'tree_settings', 'اسمح للزوار بمشاهدة ألبوم صور العائلة'),
('tree_settings.gallery_sharing_premium_desc', 'en', 'tree_settings', 'Allow visitors to view family photo album'),
('tree_settings.allow_visitors_view_album', 'ar', 'tree_settings', 'السماح للزوار بمشاهدة ألبوم الصور'),
('tree_settings.allow_visitors_view_album', 'en', 'tree_settings', 'Allow visitors to view photo album'),
('tree_settings.gallery_sharing_desc', 'ar', 'tree_settings', 'عند التفعيل، سيتمكن زوار الشجرة من رؤية جميع صور الألبوم'),
('tree_settings.gallery_sharing_desc', 'en', 'tree_settings', 'When enabled, tree visitors can see all album photos'),
('tree_settings.gallery_sharing_enabled', 'ar', 'tree_settings', 'تم تفعيل المشاركة'),
('tree_settings.gallery_sharing_enabled', 'en', 'tree_settings', 'Sharing Enabled'),
('tree_settings.gallery_now_available', 'ar', 'tree_settings', 'أصبح ألبوم الصور متاحاً للزوار'),
('tree_settings.gallery_now_available', 'en', 'tree_settings', 'Photo album is now available to visitors'),
('tree_settings.gallery_sharing_disabled', 'ar', 'tree_settings', 'تم إلغاء المشاركة'),
('tree_settings.gallery_sharing_disabled', 'en', 'tree_settings', 'Sharing Disabled'),
('tree_settings.gallery_no_longer_available', 'ar', 'tree_settings', 'لم يعد ألبوم الصور متاحاً للزوار'),
('tree_settings.gallery_no_longer_available', 'en', 'tree_settings', 'Photo album is no longer available to visitors'),
('tree_settings.gallery_update_error', 'ar', 'tree_settings', 'حدث خطأ أثناء تحديث إعدادات المشاركة'),
('tree_settings.gallery_update_error', 'en', 'tree_settings', 'Error updating sharing settings'),
('tree_settings.gallery_enabled_badge', 'ar', 'tree_settings', 'مفعل'),
('tree_settings.gallery_enabled_badge', 'en', 'tree_settings', 'Enabled'),
('tree_settings.gallery_disabled_badge', 'ar', 'tree_settings', 'معطل'),
('tree_settings.gallery_disabled_badge', 'en', 'tree_settings', 'Disabled'),
('tree_settings.gallery_warning_title', 'ar', 'tree_settings', 'تنبيه:'),
('tree_settings.gallery_warning_title', 'en', 'tree_settings', 'Warning:'),
('tree_settings.gallery_warning_desc', 'ar', 'tree_settings', 'جميع صور ألبوم العائلة ستكون مرئية لأي شخص يزور الشجرة. تأكد من أن الصور مناسبة للمشاركة العامة.'),
('tree_settings.gallery_warning_desc', 'en', 'tree_settings', 'All family album photos will be visible to anyone visiting the tree. Make sure photos are appropriate for public sharing.'),

-- Password Protection Section
('tree_settings.password_protection_title', 'ar', 'tree_settings', 'حماية بكلمة المرور'),
('tree_settings.password_protection_title', 'en', 'tree_settings', 'Password Protection'),
('tree_settings.password_protection_premium_desc', 'ar', 'tree_settings', 'احمِ شجرتك بكلمة مرور لمنع الوصول غير المصرح'),
('tree_settings.password_protection_premium_desc', 'en', 'tree_settings', 'Protect your tree with a password to prevent unauthorized access'),
('tree_settings.password_placeholder', 'ar', 'tree_settings', 'أدخل كلمة مرور قوية...'),
('tree_settings.password_placeholder', 'en', 'tree_settings', 'Enter a strong password...'),
('tree_settings.password_unprotected_badge', 'ar', 'tree_settings', '🔓 غير محمية'),
('tree_settings.password_unprotected_badge', 'en', 'tree_settings', '🔓 Unprotected'),
('tree_settings.password_add_desc', 'ar', 'tree_settings', 'أضف كلمة مرور لحماية شجرتك من الوصول غير المصرح'),
('tree_settings.password_add_desc', 'en', 'tree_settings', 'Add a password to protect your tree from unauthorized access'),
('tree_settings.add_password', 'ar', 'tree_settings', 'إضافة كلمة مرور'),
('tree_settings.add_password', 'en', 'tree_settings', 'Add Password'),
('tree_settings.password_protected_badge', 'ar', 'tree_settings', '🔒 محمية'),
('tree_settings.password_protected_badge', 'en', 'tree_settings', '🔒 Protected'),
('tree_settings.password_protected_desc', 'ar', 'tree_settings', 'شجرتك محمية بكلمة مرور. فقط من يملك كلمة المرور يمكنه الوصول.'),
('tree_settings.password_protected_desc', 'en', 'tree_settings', 'Your tree is password protected. Only those with the password can access it.'),
('tree_settings.change_password', 'ar', 'tree_settings', 'تغيير كلمة المرور'),
('tree_settings.change_password', 'en', 'tree_settings', 'Change Password'),
('tree_settings.remove_protection', 'ar', 'tree_settings', 'إزالة الحماية'),
('tree_settings.remove_protection', 'en', 'tree_settings', 'Remove Protection'),
('tree_settings.removing_protection', 'ar', 'tree_settings', 'جاري الإزالة...'),
('tree_settings.removing_protection', 'en', 'tree_settings', 'Removing...'),

-- Upgrade Modal
('tree_settings.upgrade_required', 'ar', 'tree_settings', 'ترقية الباقة مطلوبة'),
('tree_settings.upgrade_required', 'en', 'tree_settings', 'Package Upgrade Required'),
('tree_settings.upgrade_modal_desc', 'ar', 'tree_settings', 'للوصول إلى ميزة النطاق المخصص وميزات أخرى متطورة، تحتاج إلى ترقية باقتك الحالية.'),
('tree_settings.upgrade_modal_desc', 'en', 'tree_settings', 'To access custom domain feature and other advanced features, you need to upgrade your current package.'),
('tree_settings.upgrade_features_title', 'ar', 'tree_settings', 'المميزات المتاحة بعد الترقية:'),
('tree_settings.upgrade_features_title', 'en', 'tree_settings', 'Features Available After Upgrade:'),
('tree_settings.upgrade_feature_domain', 'ar', 'tree_settings', 'نطاق مخصص لشجرة العائلة'),
('tree_settings.upgrade_feature_domain', 'en', 'tree_settings', 'Custom domain for family tree'),
('tree_settings.upgrade_feature_sharing', 'ar', 'tree_settings', 'ميزات متقدمة للمشاركة'),
('tree_settings.upgrade_feature_sharing', 'en', 'tree_settings', 'Advanced sharing features'),
('tree_settings.upgrade_feature_support', 'ar', 'tree_settings', 'دعم أولوية'),
('tree_settings.upgrade_feature_support', 'en', 'tree_settings', 'Priority support'),
('tree_settings.upgrade_feature_storage', 'ar', 'tree_settings', 'مساحة تخزين إضافية'),
('tree_settings.upgrade_feature_storage', 'en', 'tree_settings', 'Additional storage space')

ON CONFLICT (key, language_code) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = now();