-- Add all Auth page translation keys
INSERT INTO translations (key, value, language_code, category) VALUES
  -- Brand and welcome texts
  ('my_tree', 'شجرتي', 'ar', 'auth'),
  ('my_tree', 'My Tree', 'en', 'auth'),
  ('welcome_to', 'مرحباً بك في', 'ar', 'auth'),
  ('welcome_to', 'Welcome to', 'en', 'auth'),
  ('exceptional_journey', 'ابدأ رحلتك الاستثنائية في اكتشاف جذورك وبناء إرث رقمي فاخر', 'ar', 'auth'),
  ('exceptional_journey', 'Start your exceptional journey discovering your roots and building a luxury digital legacy', 'en', 'auth'),
  ('best_arabic_platform', 'مع أفضل منصة عربية لإنشاء أشجار العائلة', 'ar', 'auth'),
  ('best_arabic_platform', 'With the best Arabic platform for creating family trees', 'en', 'auth'),
  
  -- Statistics
  ('distinguished_family', 'عائلة مميزة', 'ar', 'auth'),
  ('distinguished_family', 'Distinguished Family', 'en', 'auth'),
  ('preserved_member', 'فرد محفوظ', 'ar', 'auth'),
  ('preserved_member', 'Preserved Member', 'en', 'auth'),
  ('high_security', 'آمان عالي', 'ar', 'auth'),
  ('high_security', 'High Security', 'en', 'auth'),
  
  -- Features
  ('luxury_design', 'تصميم فاخر', 'ar', 'auth'),
  ('luxury_design', 'Luxury Design', 'en', 'auth'),
  ('high_quality', 'جودة عالية', 'ar', 'auth'),
  ('high_quality', 'High Quality', 'en', 'auth'),
  ('distinctive_experience', 'تجربة مميزة', 'ar', 'auth'),
  ('distinctive_experience', 'Distinctive Experience', 'en', 'auth'),
  
  -- Headers
  ('discover_roots_platform', 'اكتشف جذورك مع أفضل منصة', 'ar', 'auth'),
  ('discover_roots_platform', 'Discover your roots with the best platform', 'en', 'auth'),
  ('join_my_tree', 'انضم إلى شجرتي', 'ar', 'auth'),
  ('join_my_tree', 'Join My Tree', 'en', 'auth'),
  ('start_exceptional_journey', 'ابدأ رحلتك الاستثنائية في بناء إرث عائلتك الرقمي', 'ar', 'auth'),
  ('start_exceptional_journey', 'Start your exceptional journey building your family''s digital legacy', 'en', 'auth'),
  
  -- Magic Link Login
  ('magic_link_login', 'تسجيل الدخول بالرمز المؤقت', 'ar', 'auth'),
  ('magic_link_login', 'Login with temporary code', 'en', 'auth'),
  ('enter_email_for_magic_link', 'أدخل بريدك الإلكتروني لإرسال رمز الدخول المؤقت', 'ar', 'auth'),
  ('enter_email_for_magic_link', 'Enter your email to receive a temporary login code', 'en', 'auth'),
  ('magic_link_info', 'سيصلك رمز مؤقت للبريد المسجل يمكنك استخدامه للدخول مباشرة', 'ar', 'auth'),
  ('magic_link_info', 'You will receive a temporary code to your registered email that you can use to login directly', 'en', 'auth'),
  ('send_magic_code', 'إرسال الرمز المؤقت', 'ar', 'auth'),
  ('send_magic_code', 'Send temporary code', 'en', 'auth'),
  ('enter_otp_code', 'أدخل الرمز المؤقت المرسل إلى', 'ar', 'auth'),
  ('enter_otp_code', 'Enter the temporary code sent to', 'en', 'auth'),
  
  -- Password Reset
  ('reset_password', 'إعادة تعيين كلمة المرور', 'ar', 'auth'),
  ('reset_password', 'Reset Password', 'en', 'auth'),
  ('enter_email_for_reset', 'أدخل بريدك الإلكتروني لإرسال رمز إعادة التعيين', 'ar', 'auth'),
  ('enter_email_for_reset', 'Enter your email to receive a reset code', 'en', 'auth'),
  ('reset_password_info', 'سنرسل لك رمزاً لإعادة تعيين كلمة المرور', 'ar', 'auth'),
  ('reset_password_info', 'We will send you a code to reset your password', 'en', 'auth'),
  ('send_reset_code', 'إرسال رمز إعادة التعيين', 'ar', 'auth'),
  ('send_reset_code', 'Send reset code', 'en', 'auth'),
  ('enter_reset_code', 'أدخل الرمز المرسل إلى', 'ar', 'auth'),
  ('enter_reset_code', 'Enter the code sent to', 'en', 'auth'),
  ('new_password', 'كلمة مرور جديدة', 'ar', 'auth'),
  ('new_password', 'New Password', 'en', 'auth'),
  ('enter_new_password', 'أدخل كلمة المرور الجديدة', 'ar', 'auth'),
  ('enter_new_password', 'Enter new password', 'en', 'auth'),
  ('confirm_password', 'تأكيد كلمة المرور', 'ar', 'auth'),
  ('confirm_password', 'Confirm Password', 'en', 'auth'),
  ('confirm_new_password', 'أكد كلمة المرور الجديدة', 'ar', 'auth'),
  ('confirm_new_password', 'Confirm new password', 'en', 'auth'),
  ('update_password', 'تحديث كلمة المرور', 'ar', 'auth'),
  ('update_password', 'Update Password', 'en', 'auth'),
  
  -- OTP Verification
  ('account_confirmation', 'تأكيد الحساب', 'ar', 'auth'),
  ('account_confirmation', 'Account Confirmation', 'en', 'auth'),
  ('enter_verification_code', 'أدخل رمز التحقق المرسل إلى', 'ar', 'auth'),
  ('enter_verification_code', 'Enter verification code sent to', 'en', 'auth'),
  ('verification_code', 'رمز التحقق', 'ar', 'auth'),
  ('verification_code', 'Verification Code', 'en', 'auth'),
  ('enter_6_digit_code', 'أدخل الرمز المكون من 6 أرقام', 'ar', 'auth'),
  ('enter_6_digit_code', 'Enter 6-digit code', 'en', 'auth'),
  ('confirm_account', 'تأكيد الحساب', 'ar', 'auth'),
  ('confirm_account', 'Confirm Account', 'en', 'auth'),
  ('resend_in', 'إعادة الإرسال خلال', 'ar', 'auth'),
  ('resend_in', 'Resend in', 'en', 'auth'),
  ('resend_code', 'إعادة إرسال الرمز', 'ar', 'auth'),
  ('resend_code', 'Resend Code', 'en', 'auth'),
  
  -- Form fields
  ('first_name', 'الاسم الأول', 'ar', 'auth'),
  ('first_name', 'First Name', 'en', 'auth'),
  ('enter_first_name', 'أدخل اسمك الأول', 'ar', 'auth'),
  ('enter_first_name', 'Enter your first name', 'en', 'auth'),
  ('last_name', 'اسم العائلة', 'ar', 'auth'),
  ('last_name', 'Last Name', 'en', 'auth'),
  ('enter_last_name', 'أدخل اسم العائلة', 'ar', 'auth'),
  ('enter_last_name', 'Enter your last name', 'en', 'auth'),
  ('email', 'البريد الإلكتروني', 'ar', 'auth'),
  ('email', 'Email', 'en', 'auth'),
  ('email_placeholder', 'example@domain.com', 'ar', 'auth'),
  ('email_placeholder', 'example@domain.com', 'en', 'auth'),
  ('phone_number', 'رقم الهاتف', 'ar', 'auth'),
  ('phone_number', 'Phone Number', 'en', 'auth'),
  ('phone_placeholder', '+966 50 123 4567', 'ar', 'auth'),
  ('phone_placeholder', '+966 50 123 4567', 'en', 'auth'),
  ('password', 'كلمة المرور', 'ar', 'auth'),
  ('password', 'Password', 'en', 'auth'),
  ('enter_password', 'أدخل كلمة المرور', 'ar', 'auth'),
  ('enter_password', 'Enter password', 'en', 'auth'),
  ('enter_strong_password', 'أدخل كلمة مرور قوية', 'ar', 'auth'),
  ('enter_strong_password', 'Enter a strong password', 'en', 'auth'),
  
  -- Buttons and actions
  ('create_account', 'إنشاء حساب', 'ar', 'auth'),
  ('create_account', 'Create Account', 'en', 'auth'),
  ('login', 'تسجيل الدخول', 'ar', 'auth'),
  ('login', 'Login', 'en', 'auth'),
  ('creating_account', 'جاري إنشاء الحساب...', 'ar', 'auth'),
  ('creating_account', 'Creating account...', 'en', 'auth'),
  ('create_new_account', 'إنشاء حساب جديد', 'ar', 'auth'),
  ('create_new_account', 'Create New Account', 'en', 'auth'),
  ('login_to_account', 'تسجيل الدخول إلى حسابك', 'ar', 'auth'),
  ('login_to_account', 'Login to your account', 'en', 'auth'),
  ('forgot_password', 'نسيت كلمة المرور؟', 'ar', 'auth'),
  ('forgot_password', 'Forgot password?', 'en', 'auth'),
  ('back_to_login', 'العودة إلى تسجيل الدخول', 'ar', 'auth'),
  ('back_to_login', 'Back to login', 'en', 'auth'),
  ('back_to_register', 'العودة إلى إنشاء الحساب', 'ar', 'auth'),
  ('back_to_register', 'Back to registration', 'en', 'auth'),
  ('back', 'رجوع', 'ar', 'auth'),
  ('back', 'Back', 'en', 'auth'),
  
  -- Status messages
  ('sending', 'جاري الإرسال...', 'ar', 'auth'),
  ('sending', 'Sending...', 'en', 'auth'),
  ('verifying', 'جاري التحقق...', 'ar', 'auth'),
  ('verifying', 'Verifying...', 'en', 'auth'),
  ('updating', 'جاري التحديث...', 'ar', 'auth'),
  ('updating', 'Updating...', 'en', 'auth'),
  ('verify_code', 'تحقق من الرمز', 'ar', 'auth'),
  ('verify_code', 'Verify Code', 'en', 'auth'),
  ('code_sent', 'تم إرسال الرمز', 'ar', 'auth'),
  ('code_sent', 'Code sent', 'en', 'auth'),
  
  -- Social login
  ('or_continue_with', 'أو متابعة باستخدام', 'ar', 'auth'),
  ('or_continue_with', 'Or continue with', 'en', 'auth'),
  ('google_sign_in', 'تسجيل الدخول بـ Google', 'ar', 'auth'),
  ('google_sign_in', 'Sign in with Google', 'en', 'auth'),
  
  -- Footer links
  ('no_account', 'ليس لديك حساب؟', 'ar', 'auth'),
  ('no_account', 'Don''t have an account?', 'en', 'auth'),
  ('create_one_now', 'أنشئ حساباً الآن', 'ar', 'auth'),
  ('create_one_now', 'Create one now', 'en', 'auth'),
  ('already_have_account', 'لديك حساب بالفعل؟', 'ar', 'auth'),
  ('already_have_account', 'Already have an account?', 'en', 'auth'),
  ('login_now', 'سجل دخولك الآن', 'ar', 'auth'),
  ('login_now', 'Login now', 'en', 'auth'),
  ('back_to_home', 'العودة إلى الصفحة الرئيسية', 'ar', 'auth'),
  ('back_to_home', 'Back to homepage', 'en', 'auth'),
  
  -- Additional messages
  ('welcome_back', 'مرحباً بعودتك', 'ar', 'auth'),
  ('welcome_back', 'Welcome back', 'en', 'auth')
ON CONFLICT (key, language_code) DO UPDATE 
  SET value = EXCLUDED.value, updated_at = now();