-- Add TreeSettingsView translations (Part 5: Password Protection)
INSERT INTO translations (key, category, language_code, value) VALUES
('tree_settings.password_protection', 'tree_settings', 'ar', 'حماية بكلمة المرور'),
('tree_settings.password_protection', 'tree_settings', 'en', 'Password Protection'),
('tree_settings.password_benefit', 'tree_settings', 'ar', 'احمِ شجرتك بكلمة مرور لمنع الوصول غير المصرح'),
('tree_settings.password_benefit', 'tree_settings', 'en', 'Protect your tree with a password to prevent unauthorized access'),
('tree_settings.password_placeholder', 'tree_settings', 'ar', 'أدخل كلمة مرور قوية...'),
('tree_settings.password_placeholder', 'tree_settings', 'en', 'Enter a strong password...'),
('tree_settings.password_not_protected', 'tree_settings', 'ar', '🔓 غير محمية'),
('tree_settings.password_not_protected', 'tree_settings', 'en', '🔓 Not Protected'),
('tree_settings.password_protected', 'tree_settings', 'ar', '🔒 محمية'),
('tree_settings.password_protected', 'tree_settings', 'en', '🔒 Protected'),
('tree_settings.add_password', 'tree_settings', 'ar', 'إضافة كلمة مرور'),
('tree_settings.add_password', 'tree_settings', 'en', 'Add Password'),
('tree_settings.change_password', 'tree_settings', 'ar', 'تغيير كلمة المرور'),
('tree_settings.change_password', 'tree_settings', 'en', 'Change Password'),
('tree_settings.remove_protection', 'tree_settings', 'ar', 'إزالة الحماية'),
('tree_settings.remove_protection', 'tree_settings', 'en', 'Remove Protection'),
('tree_settings.removing', 'tree_settings', 'ar', 'جاري الإزالة...'),
('tree_settings.removing', 'tree_settings', 'en', 'Removing...'),
('tree_settings.protected_info', 'tree_settings', 'ar', 'شجرتك محمية بكلمة مرور. فقط من يملك كلمة المرور يمكنه الوصول.'),
('tree_settings.protected_info', 'tree_settings', 'en', 'Your tree is password protected. Only those with the password can access it.'),
('tree_settings.unprotected_info', 'tree_settings', 'ar', 'أضف كلمة مرور لحماية شجرتك من الوصول غير المصرح'),
('tree_settings.unprotected_info', 'tree_settings', 'en', 'Add a password to protect your tree from unauthorized access'),
('tree_settings.password_saved', 'tree_settings', 'ar', 'تم تعيين كلمة مرور للمشاركة العامة'),
('tree_settings.password_saved', 'tree_settings', 'en', 'Password set for public sharing'),
('tree_settings.password_removed', 'tree_settings', 'ar', 'تم إزالة كلمة مرور المشاركة'),
('tree_settings.password_removed', 'tree_settings', 'en', 'Sharing password removed'),
('tree_settings.password_save_failed', 'tree_settings', 'ar', 'فشل في حفظ كلمة مرور المشاركة'),
('tree_settings.password_save_failed', 'tree_settings', 'en', 'Failed to save sharing password'),
('tree_settings.password_save_error', 'tree_settings', 'ar', 'حدث خطأ أثناء حفظ كلمة المرور'),
('tree_settings.password_save_error', 'tree_settings', 'en', 'An error occurred while saving the password'),
('tree_settings.password_deleted', 'tree_settings', 'ar', 'تم الحذف'),
('tree_settings.password_deleted', 'tree_settings', 'en', 'Deleted'),
('tree_settings.password_deleted_success', 'tree_settings', 'ar', 'تم حذف كلمة مرور المشاركة بنجاح'),
('tree_settings.password_deleted_success', 'tree_settings', 'en', 'Sharing password deleted successfully'),
('tree_settings.password_delete_failed', 'tree_settings', 'ar', 'فشل في حذف كلمة مرور المشاركة'),
('tree_settings.password_delete_failed', 'tree_settings', 'en', 'Failed to delete sharing password'),
('tree_settings.password_delete_error', 'tree_settings', 'ar', 'حدث خطأ أثناء حذف كلمة المرور'),
('tree_settings.password_delete_error', 'tree_settings', 'en', 'An error occurred while deleting the password')
ON CONFLICT (key, language_code) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = now();