-- Add time-related translations for Arabic and English
INSERT INTO translations (key, language_code, value, category) VALUES
('today', 'ar', 'اليوم', 'time'),
('today', 'en', 'Today', 'time'),
('yesterday', 'ar', 'أمس', 'time'),
('yesterday', 'en', 'Yesterday', 'time'),
('days_ago', 'ar', 'أيام', 'time'),
('days_ago', 'en', 'days ago', 'time'),
('weeks_ago', 'ar', 'أسابيع', 'time'),
('weeks_ago', 'en', 'weeks ago', 'time'),
('months_ago', 'ar', 'أشهر', 'time'),
('months_ago', 'en', 'months ago', 'time'),
('years_ago', 'ar', 'سنوات', 'time'),
('years_ago', 'en', 'years ago', 'time'),
('born', 'ar', 'المولود في', 'time'),
('born', 'en', 'Born', 'time'),
('minutes_ago', 'ar', 'دقائق', 'time'),
('minutes_ago', 'en', 'minutes ago', 'time'),
('hours_ago', 'ar', 'ساعات', 'time'),
('hours_ago', 'en', 'hours ago', 'time'),
('since', 'ar', 'منذ', 'time'),
('since', 'en', 'since', 'time'),
('ago', 'ar', 'مضت', 'time'),
('ago', 'en', 'ago', 'time');