-- Add comprehensive Dashboard translation keys
INSERT INTO public.translations (language_code, key, value, category) VALUES
-- Arabic translations for Dashboard
('ar', 'dashboard.free_package', 'باقة مجانية', 'dashboard'),
('ar', 'dashboard.error', 'خطأ', 'dashboard'),
('ar', 'dashboard.error_loading_data', 'حدث خطأ في تحميل البيانات', 'dashboard'),
('ar', 'dashboard.confirmation_error', 'خطأ في التأكيد', 'dashboard'),
('ar', 'dashboard.tree_name_confirmation', 'يجب كتابة اسم الشجرة بشكل صحيح للتأكيد', 'dashboard'),
('ar', 'dashboard.deletion_error', 'خطأ في الحذف', 'dashboard'),
('ar', 'dashboard.tree_deletion_error', 'حدث خطأ أثناء حذف شجرة العائلة', 'dashboard'),
('ar', 'dashboard.tree_not_found_error', 'لم يتم العثور على الشجرة أو ليس لديك صلاحية لحذفها', 'dashboard'),
('ar', 'dashboard.deletion_success', 'تم الحذف بنجاح', 'dashboard'),
('ar', 'dashboard.tree_deletion_success', 'تم حذف شجرة العائلة بنجاح', 'dashboard'),
('ar', 'dashboard.unexpected_error', 'حدث خطأ غير متوقع', 'dashboard'),
('ar', 'dashboard.package_prefix', 'الباقة', 'dashboard'),
('ar', 'dashboard.family_trees_section', 'أشجار العائلة', 'dashboard'),
('ar', 'dashboard.created_on', 'تم الإنشاء في', 'dashboard'),
('ar', 'dashboard.upgrade_required', 'ترقية الباقة مطلوبة', 'dashboard'),
('ar', 'dashboard.create_new_tree', 'إنشاء شجرة عائلة جديدة', 'dashboard'),
('ar', 'dashboard.reached_tree_limit', 'لقد وصلت للحد المسموح من الأشجار', 'dashboard'),
('ar', 'dashboard.upgrade_package', 'ترقية الباقة', 'dashboard'),
('ar', 'dashboard.upgrade_package_description', 'لقد وصلت للحد الأقصى المسموح في باقتك الحالية', 'dashboard'),
('ar', 'dashboard.trees_suffix', 'شجرة', 'dashboard'),
('ar', 'dashboard.upgrade_benefits', 'لإنشاء المزيد من الأشجار العائلية، يمكنك ترقية باقتك للحصول على مميزات أكثر', 'dashboard'),
('ar', 'dashboard.deletion_warning', 'سيتم حذف جميع بيانات الشجرة والذكريات المرتبطة بها نهائياً.', 'dashboard'),
('ar', 'dashboard.type_tree_name', 'لتأكيد الحذف، اكتب اسم الشجرة بالضبط:', 'dashboard'),
('ar', 'dashboard.confirm_tree_name', 'اكتب اسم الشجرة للتأكيد:', 'dashboard'),

-- English translations for Dashboard
('en', 'dashboard.free_package', 'Free Package', 'dashboard'),
('en', 'dashboard.error', 'Error', 'dashboard'),
('en', 'dashboard.error_loading_data', 'Error occurred while loading data', 'dashboard'),
('en', 'dashboard.confirmation_error', 'Confirmation Error', 'dashboard'),
('en', 'dashboard.tree_name_confirmation', 'Tree name must be typed correctly for confirmation', 'dashboard'),
('en', 'dashboard.deletion_error', 'Deletion Error', 'dashboard'),
('en', 'dashboard.tree_deletion_error', 'Error occurred while deleting family tree', 'dashboard'),
('en', 'dashboard.tree_not_found_error', 'Tree not found or you do not have permission to delete it', 'dashboard'),
('en', 'dashboard.deletion_success', 'Deleted Successfully', 'dashboard'),
('en', 'dashboard.tree_deletion_success', 'Family tree deleted successfully', 'dashboard'),
('en', 'dashboard.unexpected_error', 'Unexpected error occurred', 'dashboard'),
('en', 'dashboard.package_prefix', 'Package', 'dashboard'),
('en', 'dashboard.family_trees_section', 'Family Trees', 'dashboard'),
('en', 'dashboard.created_on', 'Created on', 'dashboard'),
('en', 'dashboard.upgrade_required', 'Package Upgrade Required', 'dashboard'),
('en', 'dashboard.create_new_tree', 'Create New Family Tree', 'dashboard'),
('en', 'dashboard.reached_tree_limit', 'You have reached the allowed tree limit', 'dashboard'),
('en', 'dashboard.upgrade_package', 'Upgrade Package', 'dashboard'),
('en', 'dashboard.upgrade_package_description', 'You have reached the maximum limit allowed in your current package', 'dashboard'),
('en', 'dashboard.trees_suffix', 'tree', 'dashboard'),
('en', 'dashboard.upgrade_benefits', 'To create more family trees, you can upgrade your package to get more features', 'dashboard'),
('en', 'dashboard.deletion_warning', 'All tree data and associated memories will be permanently deleted.', 'dashboard'),
('en', 'dashboard.type_tree_name', 'To confirm deletion, type the tree name exactly:', 'dashboard'),
('en', 'dashboard.confirm_tree_name', 'Type tree name to confirm:', 'dashboard')
ON CONFLICT (language_code, key) DO NOTHING;