
-- Add missing translation keys for Auth page
INSERT INTO translations (key, language_code, value, category) VALUES
-- Missing Auth page translations
('reset_your_password', 'ar', 'إعادة تعيين كلمة المرور', 'auth'),
('reset_your_password', 'en', 'Reset Your Password', 'auth'),
('verify_your_account', 'ar', 'تحقق من حسابك', 'auth'),
('verify_your_account', 'en', 'Verify Your Account', 'auth'),
('password_placeholder', 'ar', '••••••••', 'auth'),
('password_placeholder', 'en', '••••••••', 'auth'),
('check_email_for_code', 'ar', 'تحقق من بريدك الإلكتروني', 'auth'),
('check_email_for_code', 'en', 'Check your email for the code', 'auth'),
('dont_have_account', 'ar', 'ليس لديك حساب؟', 'auth'),
('dont_have_account', 'en', 'Don''t have an account?', 'auth'),
('rate_limit_exceeded', 'ar', 'تم تجاوز عدد المحاولات المسموحة', 'auth'),
('rate_limit_exceeded', 'en', 'Rate limit exceeded', 'auth'),
('weak_password', 'ar', 'كلمة مرور ضعيفة', 'auth'),
('weak_password', 'en', 'Weak password', 'auth'),
('failed_to_send_otp', 'ar', 'فشل إرسال رمز التحقق', 'auth'),
('failed_to_send_otp', 'en', 'Failed to send verification code', 'auth'),
('password_reset_success', 'ar', 'تم إعادة تعيين كلمة المرور بنجاح', 'auth'),
('password_reset_success', 'en', 'Password reset successfully', 'auth'),
('account_created_verify', 'ar', 'تم إنشاء الحساب، يرجى التحقق من بريدك', 'auth'),
('account_created_verify', 'en', 'Account created, please verify your email', 'auth'),
('unexpected_error', 'ar', 'حدث خطأ غير متوقع', 'auth'),
('unexpected_error', 'en', 'An unexpected error occurred', 'auth'),
('invalid_credentials', 'ar', 'بيانات الدخول غير صحيحة', 'auth'),
('invalid_credentials', 'en', 'Invalid credentials', 'auth'),
('account_suspended', 'ar', 'تم تعليق الحساب', 'auth'),
('account_suspended', 'en', 'Account suspended', 'auth'),
('signup_success', 'ar', 'تم التسجيل بنجاح', 'auth'),
('signup_success', 'en', 'Signup successful', 'auth'),
('signup_error', 'ar', 'خطأ في التسجيل', 'auth'),
('signup_error', 'en', 'Signup error', 'auth'),

-- Validation error messages (for Zod schemas)
('invalid_email_format', 'ar', 'البريد الإلكتروني غير صحيح', 'validation'),
('invalid_email_format', 'en', 'Invalid email format', 'validation'),
('password_min_6_chars', 'ar', 'كلمة المرور يجب أن تكون 6 أحرف على الأقل', 'validation'),
('password_min_6_chars', 'en', 'Password must be at least 6 characters', 'validation'),
('password_min_8_chars', 'ar', 'كلمة المرور يجب أن تكون 8 أحرف على الأقل', 'validation'),
('password_min_8_chars', 'en', 'Password must be at least 8 characters', 'validation'),
('first_name_min_2_chars', 'ar', 'الاسم الأول يجب أن يكون حرفين على الأقل', 'validation'),
('first_name_min_2_chars', 'en', 'First name must be at least 2 characters', 'validation'),
('last_name_min_2_chars', 'ar', 'الاسم الأخير يجب أن يكون حرفين على الأقل', 'validation'),
('last_name_min_2_chars', 'en', 'Last name must be at least 2 characters', 'validation'),
('passwords_dont_match', 'ar', 'كلمتا المرور غير متطابقتين', 'validation'),
('passwords_dont_match', 'en', 'Passwords don''t match', 'validation'),

-- Password strength indicators
('password_strength', 'ar', 'قوة كلمة المرور', 'auth'),
('password_strength', 'en', 'Password strength', 'auth'),
('very_weak', 'ar', 'ضعيفة جداً', 'auth'),
('very_weak', 'en', 'Very weak', 'auth'),
('fair', 'ar', 'مقبولة', 'auth'),
('fair', 'en', 'Fair', 'auth'),
('good', 'ar', 'جيدة', 'auth'),
('good', 'en', 'Good', 'auth'),
('strong', 'ar', 'قوية', 'auth'),
('strong', 'en', 'Strong', 'auth')
ON CONFLICT (key, language_code) DO NOTHING;
