-- Add missing translation keys for Tree Settings components

-- Tree Settings View translations
INSERT INTO public.translations (key, value, language_code, category) VALUES
-- Back button and header
('tree_settings.back_button', 'العودة', 'ar', 'tree_settings'),
('tree_settings.back_button', 'Back', 'en', 'tree_settings'),
('tree_settings.title', 'إعدادات الشجرة', 'ar', 'tree_settings'),
('tree_settings.title', 'Tree Settings', 'en', 'tree_settings'),
('tree_settings.family_prefix', 'عائلة', 'ar', 'tree_settings'),
('tree_settings.family_prefix', 'Family', 'en', 'tree_settings'),
('tree_settings.unknown', 'غير محدد', 'ar', 'tree_settings'),
('tree_settings.unknown', 'Unknown', 'en', 'tree_settings'),

-- Family Description section
('tree_settings.family_description', 'وصف العائلة', 'ar', 'tree_settings'),
('tree_settings.family_description', 'Family Description', 'en', 'tree_settings'),
('tree_settings.family_description_desc', 'أضف وصفاً مختصراً عن تاريخ عائلتك', 'ar', 'tree_settings'),
('tree_settings.family_description_desc', 'Add a brief description about your family history', 'en', 'tree_settings'),
('tree_settings.description_placeholder', 'أدخل وصف العائلة...', 'ar', 'tree_settings'),
('tree_settings.description_placeholder', 'Enter family description...', 'en', 'tree_settings'),
('tree_settings.saving', 'جاري الحفظ...', 'ar', 'tree_settings'),
('tree_settings.saving', 'Saving...', 'en', 'tree_settings'),
('tree_settings.save', 'حفظ', 'ar', 'tree_settings'),
('tree_settings.save', 'Save', 'en', 'tree_settings'),
('tree_settings.cancel', 'إلغاء', 'ar', 'tree_settings'),
('tree_settings.cancel', 'Cancel', 'en', 'tree_settings'),
('tree_settings.edit_description', 'تعديل الوصف', 'ar', 'tree_settings'),
('tree_settings.edit_description', 'Edit Description', 'en', 'tree_settings'),

-- Share Settings section
('tree_settings.share_settings_title', 'إعدادات المشاركة والنطاق', 'ar', 'tree_settings'),
('tree_settings.share_settings_title', 'Sharing & Domain Settings', 'en', 'tree_settings'),
('tree_settings.share_settings_desc', 'تحكم في كيفية مشاركة شجرة العائلة ونطاقها المخصص', 'ar', 'tree_settings'),
('tree_settings.share_settings_desc', 'Control how your family tree is shared and its custom domain', 'en', 'tree_settings'),
('tree_settings.public_share_link', 'الرابط العام للشجرة', 'ar', 'tree_settings'),
('tree_settings.public_share_link', 'Public Tree Link', 'en', 'tree_settings'),
('tree_settings.generate_new_link', 'توليد رابط جديد', 'ar', 'tree_settings'),
('tree_settings.generate_new_link', 'Generate New Link', 'en', 'tree_settings'),
('tree_settings.share', 'مشاركة', 'ar', 'tree_settings'),
('tree_settings.share', 'Share', 'en', 'tree_settings'),
('tree_settings.expires_in', 'ينتهي في:', 'ar', 'tree_settings'),
('tree_settings.expires_in', 'Expires at:', 'en', 'tree_settings'),
('tree_settings.public_link_desc', 'يمكن لأي شخص عرض الشجرة باستخدام هذا الرابط (صالح لمدة ساعتين)', 'ar', 'tree_settings'),
('tree_settings.public_link_desc', 'Anyone can view the tree using this link (valid for 2 hours)', 'en', 'tree_settings'),

-- Custom Domain section
('tree_settings.custom_domain_title', 'الرابط المخصص', 'ar', 'tree_settings'),
('tree_settings.custom_domain_title', 'Custom Link', 'en', 'tree_settings'),
('tree_settings.custom_domain_available', 'متاح', 'ar', 'tree_settings'),
('tree_settings.custom_domain_available', 'Available', 'en', 'tree_settings'),
('tree_settings.add_custom_domain', 'إضافة رابط مخصص لشجرتك', 'ar', 'tree_settings'),
('tree_settings.add_custom_domain', 'Add a custom link for your tree', 'en', 'tree_settings'),
('tree_settings.choose_domain_example', 'اختر رابطاً سهلاً مثل: https://shjrti.com/my-family', 'ar', 'tree_settings'),
('tree_settings.choose_domain_example', 'Choose an easy link like: https://shjrti.com/my-family', 'en', 'tree_settings'),

-- Gallery Sharing section
('tree_settings.share_gallery_title', 'مشاركة ألبوم صور العائلة', 'ar', 'tree_settings'),
('tree_settings.share_gallery_title', 'Share Family Photo Album', 'en', 'tree_settings'),
('tree_settings.share_gallery_desc', 'السماح للزوار بمشاهدة ألبوم الصور', 'ar', 'tree_settings'),
('tree_settings.share_gallery_desc', 'Allow visitors to view photo album', 'en', 'tree_settings'),
('tree_settings.share_gallery_enabled_desc', 'عند التفعيل، سيتمكن زوار الشجرة من رؤية جميع صور الألبوم', 'ar', 'tree_settings'),
('tree_settings.share_gallery_enabled_desc', 'When enabled, tree visitors can see all album photos', 'en', 'tree_settings'),
('tree_settings.enabled', 'مفعل', 'ar', 'tree_settings'),
('tree_settings.enabled', 'Enabled', 'en', 'tree_settings'),
('tree_settings.gallery_warning', 'تنبيه: جميع صور ألبوم العائلة ستكون مرئية لأي شخص يزور الشجرة. تأكد من أن الصور مناسبة للمشاركة العامة.', 'ar', 'tree_settings'),
('tree_settings.gallery_warning', 'Warning: All family album photos will be visible to anyone visiting the tree. Make sure photos are appropriate for public sharing.', 'en', 'tree_settings'),
('tree_settings.gallery_warning_title', 'تنبيه:', 'ar', 'tree_settings'),
('tree_settings.gallery_warning_title', 'Warning:', 'en', 'tree_settings'),

-- Password Protection section
('tree_settings.password_protection_title', 'حماية بكلمة المرور', 'ar', 'tree_settings'),
('tree_settings.password_protection_title', 'Password Protection', 'en', 'tree_settings'),
('tree_settings.password_protection_premium', '👑 Premium', 'ar', 'tree_settings'),
('tree_settings.password_protection_premium', '👑 Premium', 'en', 'tree_settings'),
('tree_settings.password_protection_desc', 'احمِ شجرتك بكلمة مرور لمنع الوصول غير المصرح', 'ar', 'tree_settings'),
('tree_settings.password_protection_desc', 'Protect your tree with a password to prevent unauthorized access', 'en', 'tree_settings'),
('tree_settings.password_placeholder', 'أدخل كلمة مرور قوية...', 'ar', 'tree_settings'),
('tree_settings.password_placeholder', 'Enter a strong password...', 'en', 'tree_settings'),
('tree_settings.upgrade_now', 'ترقية الآن', 'ar', 'tree_settings'),
('tree_settings.upgrade_now', 'Upgrade Now', 'en', 'tree_settings'),
('tree_settings.password_not_protected', '🔓 غير محمية', 'ar', 'tree_settings'),
('tree_settings.password_not_protected', '🔓 Not Protected', 'en', 'tree_settings'),
('tree_settings.add_password_desc', 'أضف كلمة مرور لحماية شجرتك من الوصول غير المصرح', 'ar', 'tree_settings'),
('tree_settings.add_password_desc', 'Add a password to protect your tree from unauthorized access', 'en', 'tree_settings'),
('tree_settings.add_password_button', 'إضافة كلمة مرور', 'ar', 'tree_settings'),
('tree_settings.add_password_button', 'Add Password', 'en', 'tree_settings'),
('tree_settings.protected_status', '🔒 محمية', 'ar', 'tree_settings'),
('tree_settings.protected_status', '🔒 Protected', 'en', 'tree_settings'),
('tree_settings.edit_password_button', 'تعديل', 'ar', 'tree_settings'),
('tree_settings.edit_password_button', 'Edit', 'en', 'tree_settings'),
('tree_settings.remove_password', 'إزالة كلمة المرور', 'ar', 'tree_settings'),
('tree_settings.remove_password', 'Remove Password', 'en', 'tree_settings'),

-- Edit Suggestions section
('tree_settings.edit_suggestions_title', 'اقتراحات التعديل', 'ar', 'tree_settings'),
('tree_settings.edit_suggestions_title', 'Edit Suggestions', 'en', 'tree_settings'),
('tree_settings.edit_suggestions_desc', 'راجع اقتراحات التعديل من زوار الشجرة', 'ar', 'tree_settings'),
('tree_settings.edit_suggestions_desc', 'Review edit suggestions from tree visitors', 'en', 'tree_settings'),
('tree_settings.suggested_edits', 'التعديلات المقترحة', 'ar', 'tree_settings'),
('tree_settings.suggested_edits', 'Suggested Edits', 'en', 'tree_settings'),
('tree_settings.no_pending_suggestions', 'لا توجد اقتراحات معلقة', 'ar', 'tree_settings'),
('tree_settings.no_pending_suggestions', 'No pending suggestions', 'en', 'tree_settings'),
('tree_settings.all_suggestions', 'جميع الاقتراحات', 'ar', 'tree_settings'),
('tree_settings.all_suggestions', 'All Suggestions', 'en', 'tree_settings'),
('tree_settings.no_suggestions_found', 'لا توجد اقتراحات', 'ar', 'tree_settings'),
('tree_settings.no_suggestions_found', 'No suggestions found', 'en', 'tree_settings'),

-- Advanced Settings section
('tree_settings.advanced_settings', 'إعدادات متقدمة', 'ar', 'tree_settings'),
('tree_settings.advanced_settings', 'Advanced Settings', 'en', 'tree_settings'),
('tree_settings.advanced_options_soon', 'خيارات إضافية (قريباً)', 'ar', 'tree_settings'),
('tree_settings.advanced_options_soon', 'Additional options (coming soon)', 'en', 'tree_settings'),
('tree_settings.export_tree_data', 'تصدير بيانات الشجرة', 'ar', 'tree_settings'),
('tree_settings.export_tree_data', 'Export Tree Data', 'en', 'tree_settings'),
('tree_settings.delete_tree_permanently', 'حذف الشجرة نهائياً', 'ar', 'tree_settings'),
('tree_settings.delete_tree_permanently', 'Delete Tree Permanently', 'en', 'tree_settings'),
('tree_settings.delete_warning', 'تحذير: هذا الإجراء لا يمكن التراجع عنه', 'ar', 'tree_settings'),
('tree_settings.delete_warning', 'Warning: This action cannot be undone', 'en', 'tree_settings'),

-- Toast messages
('tree_settings.toast.public_link_copied', 'تم نسخ الرابط العام', 'ar', 'tree_settings'),
('tree_settings.toast.public_link_copied', 'Public Link Copied', 'en', 'tree_settings'),
('tree_settings.toast.public_link_copied_desc', 'تم نسخ رابط المشاركة العام إلى الحافظة', 'ar', 'tree_settings'),
('tree_settings.toast.public_link_copied_desc', 'Public share link copied to clipboard', 'en', 'tree_settings'),
('tree_settings.toast.custom_domain_copied', 'تم نسخ الرابط المخصص', 'ar', 'tree_settings'),
('tree_settings.toast.custom_domain_copied', 'Custom Link Copied', 'en', 'tree_settings'),
('tree_settings.toast.custom_domain_copied_desc', 'تم نسخ رابط النطاق المخصص بنجاح', 'ar', 'tree_settings'),
('tree_settings.toast.custom_domain_copied_desc', 'Custom domain link copied successfully', 'en', 'tree_settings'),
('tree_settings.toast.share_title', 'شجرة عائلة {name}', 'ar', 'tree_settings'),
('tree_settings.toast.share_title', 'Family Tree of {name}', 'en', 'tree_settings'),
('tree_settings.toast.error', 'خطأ', 'ar', 'tree_settings'),
('tree_settings.toast.error', 'Error', 'en', 'tree_settings'),
('tree_settings.toast.description_save_failed', 'فشل في حفظ وصف العائلة', 'ar', 'tree_settings'),
('tree_settings.toast.description_save_failed', 'Failed to save family description', 'en', 'tree_settings'),
('tree_settings.toast.saved', 'تم الحفظ', 'ar', 'tree_settings'),
('tree_settings.toast.saved', 'Saved', 'en', 'tree_settings'),
('tree_settings.toast.description_saved', 'تم حفظ وصف العائلة بنجاح', 'ar', 'tree_settings'),
('tree_settings.toast.description_saved', 'Family description saved successfully', 'en', 'tree_settings'),
('tree_settings.toast.description_save_error', 'حدث خطأ أثناء حفظ وصف العائلة', 'ar', 'tree_settings'),
('tree_settings.toast.description_save_error', 'An error occurred while saving family description', 'en', 'tree_settings'),
('tree_settings.toast.password_save_failed', 'فشل في حفظ كلمة مرور المشاركة', 'ar', 'tree_settings'),
('tree_settings.toast.password_save_failed', 'Failed to save share password', 'en', 'tree_settings'),
('tree_settings.toast.password_saved', 'تم تعيين كلمة مرور للمشاركة العامة', 'ar', 'tree_settings'),
('tree_settings.toast.password_saved', 'Password set for public sharing', 'en', 'tree_settings'),
('tree_settings.toast.password_removed', 'تم إزالة كلمة مرور المشاركة', 'ar', 'tree_settings'),
('tree_settings.toast.password_removed', 'Share password removed', 'en', 'tree_settings'),
('tree_settings.toast.password_save_error', 'حدث خطأ أثناء حفظ كلمة المرور', 'ar', 'tree_settings'),
('tree_settings.toast.password_save_error', 'An error occurred while saving password', 'en', 'tree_settings'),
('tree_settings.toast.password_deleted', 'تم حذف كلمة المرور بنجاح', 'ar', 'tree_settings'),
('tree_settings.toast.password_deleted', 'Password deleted successfully', 'en', 'tree_settings'),
('tree_settings.toast.password_delete_failed', 'فشل في حذف كلمة المرور', 'ar', 'tree_settings'),
('tree_settings.toast.password_delete_failed', 'Failed to delete password', 'en', 'tree_settings'),
('tree_settings.toast.gallery_update_error', 'حدث خطأ في تحديث إعدادات المعرض', 'ar', 'tree_settings'),
('tree_settings.toast.gallery_update_error', 'Error updating gallery settings', 'en', 'tree_settings'),
('tree_settings.toast.gallery_updated', 'تم تحديث إعدادات معرض الصور', 'ar', 'tree_settings'),
('tree_settings.toast.gallery_updated', 'Gallery settings updated', 'en', 'tree_settings'),
('tree_settings.toast.domain_saved', 'تم حفظ النطاق المخصص', 'ar', 'tree_settings'),
('tree_settings.toast.domain_saved', 'Custom domain saved', 'en', 'tree_settings'),
('tree_settings.toast.domain_set', 'تم تعيين النطاق: {domain}', 'ar', 'tree_settings'),
('tree_settings.toast.domain_set', 'Domain set: {domain}', 'en', 'tree_settings'),
('tree_settings.toast.domain_removed', 'تم إزالة النطاق المخصص', 'ar', 'tree_settings'),
('tree_settings.toast.domain_removed', 'Custom domain removed', 'en', 'tree_settings'),
('tree_settings.toast.domain_save_error', 'خطأ في حفظ النطاق', 'ar', 'tree_settings'),
('tree_settings.toast.domain_save_error', 'Error saving domain', 'en', 'tree_settings'),
('tree_settings.toast.domain_save_error_desc', 'حدث خطأ أثناء حفظ النطاق المخصص', 'ar', 'tree_settings'),
('tree_settings.toast.domain_save_error_desc', 'An error occurred while saving custom domain', 'en', 'tree_settings'),

-- Custom Domain Modal translations
('custom_domain.validation.chars_only', 'يمكن استخدام الحروف والأرقام والشرطات فقط (مثال: my-family)', 'ar', 'custom_domain'),
('custom_domain.validation.chars_only', 'Only letters, numbers, and hyphens allowed (example: my-family)', 'en', 'custom_domain'),
('custom_domain.validation.min_length', 'يجب أن يكون الرابط 3 أحرف على الأقل', 'ar', 'custom_domain'),
('custom_domain.validation.min_length', 'Link must be at least 3 characters', 'en', 'custom_domain'),
('custom_domain.validation.max_length', 'يجب أن يكون الرابط 30 حرف كحد أقصى', 'ar', 'custom_domain'),
('custom_domain.validation.max_length', 'Link must be maximum 30 characters', 'en', 'custom_domain'),
('custom_domain.validation.already_taken', 'هذا الرابط مستخدم بالفعل، الرجاء اختيار رابط آخر', 'ar', 'custom_domain'),
('custom_domain.validation.already_taken', 'This link is already taken, please choose another', 'en', 'custom_domain'),
('custom_domain.validation.available', 'الرابط متاح ويمكن استخدامه', 'ar', 'custom_domain'),
('custom_domain.validation.available', 'Link is available and can be used', 'en', 'custom_domain'),
('custom_domain.validation.check_error', 'حدث خطأ أثناء التحقق من الرابط', 'ar', 'custom_domain'),
('custom_domain.validation.check_error', 'An error occurred while validating the link', 'en', 'custom_domain'),

-- Share Link Modal translations
('share_link.generation_failed', 'فشل في إنشاء رابط المشاركة', 'ar', 'share_link'),
('share_link.generation_failed', 'Failed to generate share link', 'en', 'share_link')

ON CONFLICT (key, language_code) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = now();