-- Insert English and Arabic translations for home page
INSERT INTO translations (language_code, key, value, category) VALUES
-- Hero Section - English
('en', 'hero_badge', 'Next Generation Heritage Preservation', 'homepage'),
('en', 'hero_title_1', 'Discover', 'homepage'),
('en', 'hero_title_2', 'Your Family History', 'homepage'),
('en', 'hero_description', 'An extraordinary journey through time to explore your roots and build a digital legacy that lasts forever. Preserve your ancestors'' stories and share them with future generations.', 'homepage'),
('en', 'hero_cta_primary', 'Start Your Journey Now', 'homepage'),
('en', 'hero_cta_secondary', 'Watch Demo', 'homepage'),
('en', 'stat_1_number', '+1000', 'homepage'),
('en', 'stat_1_label', 'Happy Families', 'homepage'),
('en', 'stat_2_number', '+5000', 'homepage'),
('en', 'stat_2_label', 'Preserved Members', 'homepage'),
('en', 'stat_3_number', '99%', 'homepage'),
('en', 'stat_3_label', 'User Satisfaction', 'homepage'),
('en', 'hero_image_alt', 'Innovative Family Tree', 'homepage'),
('en', 'floating_card_1', 'Preserved Memories', 'homepage'),
('en', 'floating_card_2', 'Rich History', 'homepage'),

-- Features Section - English
('en', 'features_badge', 'Best in the Arab World', 'homepage'),
('en', 'features_title_1', 'Why Are We', 'homepage'),
('en', 'features_title_2', 'Special?', 'homepage'),
('en', 'features_description', 'We combine authenticity and modernity to offer you a unique experience in preserving your family heritage', 'homepage'),
('en', 'feature_1_title', 'Luxury Family Legacy', 'homepage'),
('en', 'feature_1_description', 'Preserve your family history in an elegant and distinguished style', 'homepage'),
('en', 'feature_2_title', 'Precious Memories', 'homepage'),
('en', 'feature_2_description', 'Photos, stories and details that preserve your cherished memories', 'homepage'),
('en', 'feature_3_title', 'Advanced Protection', 'homepage'),
('en', 'feature_3_description', 'High security and complete protection for your personal data', 'homepage'),
('en', 'feature_4_title', 'Forever', 'homepage'),
('en', 'feature_4_description', 'Your family history preserved forever for future generations', 'homepage'),
('en', 'features_cta', 'An exceptional experience awaits you', 'homepage'),

-- Memory Section - English
('en', 'memory_section_image_alt', 'Memory Preservation', 'homepage'),
('en', 'memory_section_title_1', 'Your Memories Are Safe', 'homepage'),
('en', 'memory_section_title_2', 'Forever', 'homepage'),
('en', 'memory_section_description', 'We understand that every photo and every story has invaluable worth. That''s why we provide the highest levels of protection and security to ensure your memories remain preserved forever.', 'homepage'),
('en', 'memory_feature_1', 'Bank-level advanced encryption', 'homepage'),
('en', 'memory_feature_2', 'Automatic cloud backup', 'homepage'),
('en', 'memory_feature_3', 'Secure access for all family members', 'homepage'),
('en', 'future_family_image_alt', 'Future Family', 'homepage'),

-- Testimonials Section - English
('en', 'testimonials_badge', 'Real testimonials from our clients', 'homepage'),
('en', 'testimonials_title_1', 'What Do Our', 'homepage'),
('en', 'testimonials_title_2', 'Clients Say?', 'homepage'),
('en', 'testimonial_1_name', 'Ahmed Al-Saad', 'homepage'),
('en', 'testimonial_1_role', 'Father of Family', 'homepage'),
('en', 'testimonial_1_text', 'Amazing app that helped me gather my family history and preserve it for future generations. Now my children know their grandparents'' stories.', 'homepage'),
('en', 'testimonial_2_name', 'Fatima Al-Ahmad', 'homepage'),
('en', 'testimonial_2_role', 'Mother of Four Children', 'homepage'),
('en', 'testimonial_2_text', 'Easy and beautiful interface, I was able to create a complete family tree with all details and photos. Highly recommend it.', 'homepage'),
('en', 'testimonial_3_name', 'Mohammed Al-Ali', 'homepage'),
('en', 'testimonial_3_role', 'Genealogy Researcher', 'homepage'),
('en', 'testimonial_3_text', 'Perfect tool for genealogy researchers. Advanced capabilities and excellent organization of information.', 'homepage'),
('en', 'trust_indicator_1', 'Trusted by +1000 families', 'homepage'),
('en', 'trust_indicator_2', '5-star rating', 'homepage'),
('en', 'trust_indicator_3', 'Best in the region', 'homepage'),

-- Newsletter Section - English
('en', 'newsletter_badge', 'Exclusive Newsletter', 'homepage'),
('en', 'newsletter_title', 'Stay Connected With Us', 'homepage'),
('en', 'newsletter_description', 'Get the latest tips and new features for building your perfect family tree', 'homepage'),
('en', 'newsletter_email_placeholder', 'Email Address', 'homepage'),
('en', 'newsletter_loading', 'Sending...', 'homepage'),
('en', 'newsletter_subscribe_button', 'Subscribe', 'homepage'),
('en', 'newsletter_thank_you', 'Thank you! You have been successfully registered for the newsletter', 'homepage'),
('en', 'newsletter_trust_1', '100% Secure', 'homepage'),
('en', 'newsletter_trust_2', 'No Spam', 'homepage'),
('en', 'newsletter_trust_3', 'Exclusive Content', 'homepage'),
('en', 'newsletter_error_title', 'Email Error', 'homepage'),
('en', 'newsletter_error_invalid', 'Please enter a valid email address', 'homepage'),
('en', 'newsletter_already_subscribed_title', 'Already Subscribed', 'homepage'),
('en', 'newsletter_already_subscribed', 'You are already subscribed to the newsletter', 'homepage'),
('en', 'newsletter_success_title', 'Successfully Subscribed', 'homepage'),
('en', 'newsletter_success', 'Thank you! You have been added to the newsletter', 'homepage'),
('en', 'newsletter_error_general', 'An error occurred, please try again', 'homepage'),

-- Hero Section - Arabic (existing)
('ar', 'hero_badge', 'الجيل الجديد من حفظ التراث', 'homepage'),
('ar', 'hero_title_1', 'اكتشف', 'homepage'),
('ar', 'hero_title_2', 'تاريخ عائلتك', 'homepage'),
('ar', 'hero_description', 'رحلة استثنائية عبر الزمن لاستكشاف جذورك وبناء إرث رقمي يدوم للأبد. احفظ قصص أجدادك وشاركها مع الأجيال القادمة.', 'homepage'),
('ar', 'hero_cta_primary', 'ابدأ رحلتك الآن', 'homepage'),
('ar', 'hero_cta_secondary', 'شاهد العرض التوضيحي', 'homepage'),
('ar', 'stat_1_number', '+١٠٠٠', 'homepage'),
('ar', 'stat_1_label', 'عائلة سعيدة', 'homepage'),
('ar', 'stat_2_number', '+٥٠٠٠', 'homepage'),
('ar', 'stat_2_label', 'فرد محفوظ', 'homepage'),
('ar', 'stat_3_number', '٩٩٪', 'homepage'),
('ar', 'stat_3_label', 'رضا المستخدمين', 'homepage'),
('ar', 'hero_image_alt', 'شجرة العائلة المبتكرة', 'homepage'),
('ar', 'floating_card_1', 'ذكريات محفوظة', 'homepage'),
('ar', 'floating_card_2', 'تاريخ عريق', 'homepage'),

-- Features Section - Arabic (existing)
('ar', 'features_badge', 'الأفضل في العالم العربي', 'homepage'),
('ar', 'features_title_1', 'لماذا نحن', 'homepage'),
('ar', 'features_title_2', 'مميزون؟', 'homepage'),
('ar', 'features_description', 'نجمع بين الأصالة والحداثة لنقدم لك تجربة فريدة في حفظ تراث عائلتك', 'homepage'),
('ar', 'feature_1_title', 'إرث عائلي فاخر', 'homepage'),
('ar', 'feature_1_description', 'احفظ تاريخ عائلتك بأسلوب راقي ومميز', 'homepage'),
('ar', 'feature_2_title', 'ذكريات ثمينة', 'homepage'),
('ar', 'feature_2_description', 'صور وقصص وتفاصيل تحافظ على ذكرياتك الغالية', 'homepage'),
('ar', 'feature_3_title', 'حماية متقدمة', 'homepage'),
('ar', 'feature_3_description', 'أمان عالي وحماية كاملة لبياناتك الشخصية', 'homepage'),
('ar', 'feature_4_title', 'للأبد', 'homepage'),
('ar', 'feature_4_description', 'تاريخ عائلتك محفوظ إلى الأبد للأجيال القادمة', 'homepage'),
('ar', 'features_cta', 'تجربة استثنائية تنتظرك', 'homepage'),

-- Memory Section - Arabic (existing)
('ar', 'memory_section_image_alt', 'حفظ الذكريات', 'homepage'),
('ar', 'memory_section_title_1', 'ذكرياتك في أمان', 'homepage'),
('ar', 'memory_section_title_2', 'للأبد', 'homepage'),
('ar', 'memory_section_description', 'نحن نفهم أن كل صورة وكل قصة لها قيمة لا تقدر بثمن. لذلك نوفر أعلى مستويات الحماية والأمان لضمان بقاء ذكرياتك محفوظة إلى الأبد.', 'homepage'),
('ar', 'memory_feature_1', 'تشفير متقدم على مستوى البنوك', 'homepage'),
('ar', 'memory_feature_2', 'نسخ احتياطي تلقائي في السحابة', 'homepage'),
('ar', 'memory_feature_3', 'وصول آمن لجميع أفراد العائلة', 'homepage'),
('ar', 'future_family_image_alt', 'مستقبل العائلة', 'homepage'),

-- Testimonials Section - Arabic (existing)
('ar', 'testimonials_badge', 'شهادات حقيقية من عملائنا', 'homepage'),
('ar', 'testimonials_title_1', 'ماذا يقول', 'homepage'),
('ar', 'testimonials_title_2', 'عملاؤنا؟', 'homepage'),
('ar', 'testimonial_1_name', 'أحمد السعد', 'homepage'),
('ar', 'testimonial_1_role', 'رب عائلة', 'homepage'),
('ar', 'testimonial_1_text', 'تطبيق رائع ساعدني في جمع تاريخ عائلتي وحفظه للأجيال القادمة. الآن أطفالي يعرفون قصص أجدادهم.', 'homepage'),
('ar', 'testimonial_2_name', 'فاطمة الأحمد', 'homepage'),
('ar', 'testimonial_2_role', 'أم لأربعة أطفال', 'homepage'),
('ar', 'testimonial_2_text', 'واجهة سهلة وجميلة، استطعت إنشاء شجرة عائلة كاملة بكل التفاصيل والصور. أنصح به بشدة.', 'homepage'),
('ar', 'testimonial_3_name', 'محمد العلي', 'homepage'),
('ar', 'testimonial_3_role', 'باحث في الأنساب', 'homepage'),
('ar', 'testimonial_3_text', 'أداة مثالية للباحثين في الأنساب. إمكانيات متقدمة وتنظيم رائع للمعلومات.', 'homepage'),
('ar', 'trust_indicator_1', 'موثوق من +١٠٠٠ عائلة', 'homepage'),
('ar', 'trust_indicator_2', 'تقييم ٥ نجوم', 'homepage'),
('ar', 'trust_indicator_3', 'الأفضل في المنطقة', 'homepage'),

-- Newsletter Section - Arabic (existing)
('ar', 'newsletter_badge', 'نيوزليتر حصري', 'homepage'),
('ar', 'newsletter_title', 'ابق على تواصل معنا', 'homepage'),
('ar', 'newsletter_description', 'احصل على أحدث النصائح والميزات الجديدة لبناء شجرة عائلتك المثالية', 'homepage'),
('ar', 'newsletter_email_placeholder', 'البريد الإلكتروني', 'homepage'),
('ar', 'newsletter_loading', 'جاري الإرسال...', 'homepage'),
('ar', 'newsletter_subscribe_button', 'اشتراك', 'homepage'),
('ar', 'newsletter_thank_you', 'شكراً لك! تم تسجيلك بنجاح في النشرة الإخبارية', 'homepage'),
('ar', 'newsletter_trust_1', 'آمن 100%', 'homepage'),
('ar', 'newsletter_trust_2', 'بدون إزعاج', 'homepage'),
('ar', 'newsletter_trust_3', 'محتوى حصري', 'homepage'),
('ar', 'newsletter_error_title', 'خطأ في البريد الإلكتروني', 'homepage'),
('ar', 'newsletter_error_invalid', 'يرجى إدخال بريد إلكتروني صحيح', 'homepage'),
('ar', 'newsletter_already_subscribed_title', 'مشترك بالفعل', 'homepage'),
('ar', 'newsletter_already_subscribed', 'أنت مشترك بالفعل في النشرة الإخبارية', 'homepage'),
('ar', 'newsletter_success_title', 'تم الاشتراك بنجاح', 'homepage'),
('ar', 'newsletter_success', 'شكراً لك! تم إضافتك إلى النشرة الإخبارية', 'homepage'),
('ar', 'newsletter_error_general', 'حدث خطأ، يرجى المحاولة مرة أخرى', 'homepage')

ON CONFLICT (language_code, key) DO UPDATE SET 
value = EXCLUDED.value,
updated_at = now();