-- Add toast message translation keys for FamilyBuilder
INSERT INTO public.translations (language_code, key, value, category) VALUES
-- Arabic toast translations
('ar', 'family_builder.error_loading_data', 'خطأ في تحميل البيانات', 'family'),
('ar', 'family_builder.error_loading_desc', 'حدث خطأ أثناء تحميل بيانات العائلة', 'family'),
('ar', 'family_builder.error_processing_image', 'خطأ في معالجة الصورة', 'family'),
('ar', 'family_builder.error_processing_image_desc', 'حدث خطأ أثناء قص الصورة', 'family'),
('ar', 'family_builder.max_limit_reached', 'تم الوصول للحد الأقصى', 'family'),
('ar', 'family_builder.max_limit_desc', 'لا يمكن إضافة أعضاء جدد. الحد الأقصى المسموح:', 'family'),
('ar', 'family_builder.member', 'عضو', 'family'),
('ar', 'family_builder.error', 'خطأ', 'family'),
('ar', 'family_builder.complete_fields', 'يرجى إكمال جميع الحقول المطلوبة (الاسم والجنس)', 'family'),
('ar', 'family_builder.error_adding_wife', 'خطأ في إضافة الزوجة', 'family'),
('ar', 'family_builder.error_adding_wife_desc', 'حدث خطأ أثناء إضافة الزوجة', 'family'),
('ar', 'family_builder.updated', 'تم التحديث', 'family'),
('ar', 'family_builder.updated_desc', 'تم تحديث بيانات العضو بنجاح', 'family'),
('ar', 'family_builder.added', 'تم الإضافة', 'family'),
('ar', 'family_builder.added_desc', 'تم إضافة', 'family'),
('ar', 'family_builder.with_wives', 'مع زوجة', 'family'),
('ar', 'family_builder.with_husbands', 'مع زوج', 'family'),
('ar', 'family_builder.to_family', 'للعائلة', 'family'),
('ar', 'family_builder.save_error', 'حدث خطأ أثناء حفظ البيانات', 'family'),
('ar', 'family_builder.warning', 'تحذير', 'family'),
('ar', 'family_builder.cannot_delete_founder', 'لا يمكن حذف مؤسس العائلة', 'family'),
('ar', 'family_builder.deleted', 'تم الحذف', 'family'),
('ar', 'family_builder.deleted_desc', 'تم حذف العضو من شجرة العائلة', 'family'),
('ar', 'family_builder.delete_error', 'حدث خطأ أثناء حذف العضو', 'family'),
('ar', 'family_builder.missing_info', 'معلومات ناقصة', 'family'),
('ar', 'family_builder.enter_name_gender', 'يرجى إدخال الاسم واختيار الجنس', 'family'),
('ar', 'family_builder.choose_related_family', 'يرجى اختيار العائلة المرتبطة للطفل', 'family'),

-- English toast translations
('en', 'family_builder.error_loading_data', 'Error Loading Data', 'family'),
('en', 'family_builder.error_loading_desc', 'Error occurred while loading family data', 'family'),
('en', 'family_builder.error_processing_image', 'Image Processing Error', 'family'),
('en', 'family_builder.error_processing_image_desc', 'Error occurred while cropping image', 'family'),
('en', 'family_builder.max_limit_reached', 'Maximum Limit Reached', 'family'),
('en', 'family_builder.max_limit_desc', 'Cannot add new members. Maximum allowed:', 'family'),
('en', 'family_builder.member', 'member', 'family'),
('en', 'family_builder.error', 'Error', 'family'),
('en', 'family_builder.complete_fields', 'Please complete all required fields (name and gender)', 'family'),
('en', 'family_builder.error_adding_wife', 'Error Adding Wife', 'family'),
('en', 'family_builder.error_adding_wife_desc', 'Error occurred while adding wife', 'family'),
('en', 'family_builder.updated', 'Updated', 'family'),
('en', 'family_builder.updated_desc', 'Member data updated successfully', 'family'),
('en', 'family_builder.added', 'Added', 'family'),
('en', 'family_builder.added_desc', 'Added', 'family'),
('en', 'family_builder.with_wives', 'with wives', 'family'),
('en', 'family_builder.with_husbands', 'with husbands', 'family'),
('en', 'family_builder.to_family', 'to family', 'family'),
('en', 'family_builder.save_error', 'Error occurred while saving data', 'family'),
('en', 'family_builder.warning', 'Warning', 'family'),
('en', 'family_builder.cannot_delete_founder', 'Cannot delete family founder', 'family'),
('en', 'family_builder.deleted', 'Deleted', 'family'),
('en', 'family_builder.deleted_desc', 'Member deleted from family tree', 'family'),
('en', 'family_builder.delete_error', 'Error occurred while deleting member', 'family'),
('en', 'family_builder.missing_info', 'Missing Information', 'family'),
('en', 'family_builder.enter_name_gender', 'Please enter name and select gender', 'family'),
('en', 'family_builder.choose_related_family', 'Please choose the related family for the child', 'family')
ON CONFLICT (language_code, key) DO NOTHING;