-- Add translation keys for Dashboard, Family Builder, and Auth pages
INSERT INTO translations (key, value, language_code, category) VALUES

-- Dashboard translations - English
('dashboard_welcome', 'Welcome', 'en', 'dashboard'),
('no_trees', 'No trees yet', 'en', 'dashboard'), 
('trees', 'trees', 'en', 'dashboard'),
('no_trees_desc', 'Start your journey building your digital family legacy', 'en', 'dashboard'),
('dashboard_welcome_badge', 'Dashboard', 'en', 'dashboard'),
('online', 'Online', 'en', 'dashboard'),
('free_account', 'Free Account', 'en', 'dashboard'),
('upgrade_account', 'Upgrade Account', 'en', 'dashboard'),
('my_family_trees', 'My Family Trees', 'en', 'dashboard'),
('create_new_tree', 'Create New Tree', 'en', 'dashboard'),
('tree_actions', 'Tree Actions', 'en', 'dashboard'),
('view_tree', 'View Tree', 'en', 'dashboard'),
('edit_tree', 'Edit Tree', 'en', 'dashboard'),
('delete_tree', 'Delete Tree', 'en', 'dashboard'),
('created_on', 'Created on', 'en', 'dashboard'),
('members_count', 'members', 'en', 'dashboard'),
('upgrade_modal_title', 'Upgrade Required', 'en', 'dashboard'),
('upgrade_modal_desc', 'You have reached the maximum number of family trees for your current plan', 'en', 'dashboard'),
('view_plans', 'View Plans', 'en', 'dashboard'),
('delete_confirmation', 'Delete Confirmation', 'en', 'dashboard'),
('delete_tree_warning', 'To confirm deletion, please type the tree name exactly as shown', 'en', 'dashboard'),
('type_tree_name', 'Type tree name to confirm', 'en', 'dashboard'),
('confirm_delete', 'Confirm Delete', 'en', 'dashboard'),
('cancel', 'Cancel', 'en', 'dashboard'),
('data_loading_error', 'Error loading data', 'en', 'dashboard'),
('delete_confirmation_error', 'Confirmation Error', 'en', 'dashboard'),
('tree_name_validation', 'You must type the tree name correctly to confirm', 'en', 'dashboard'),
('delete_error', 'Delete Error', 'en', 'dashboard'),
('delete_success', 'Deleted Successfully', 'en', 'dashboard'),
('tree_deleted_success', 'Family tree has been deleted successfully', 'en', 'dashboard'),

-- Dashboard translations - Arabic
('dashboard_welcome', 'أهلاً', 'ar', 'dashboard'),
('no_trees', 'لا توجد أشجار بعد', 'ar', 'dashboard'),
('trees', 'أشجار', 'ar', 'dashboard'),
('no_trees_desc', 'ابدأ رحلتك في بناء إرثك العائلي الرقمي', 'ar', 'dashboard'),
('dashboard_welcome_badge', 'لوحة التحكم', 'ar', 'dashboard'),
('online', 'متصل', 'ar', 'dashboard'),
('free_account', 'حساب مجاني', 'ar', 'dashboard'),
('upgrade_account', 'طوّر حسابك', 'ar', 'dashboard'),
('my_family_trees', 'أشجار عائلتي', 'ar', 'dashboard'),
('create_new_tree', 'إنشاء شجرة جديدة', 'ar', 'dashboard'),
('tree_actions', 'إجراءات الشجرة', 'ar', 'dashboard'),
('view_tree', 'عرض الشجرة', 'ar', 'dashboard'),
('edit_tree', 'تعديل الشجرة', 'ar', 'dashboard'),
('delete_tree', 'حذف الشجرة', 'ar', 'dashboard'),
('created_on', 'تم الإنشاء في', 'ar', 'dashboard'),
('members_count', 'أعضاء', 'ar', 'dashboard'),
('upgrade_modal_title', 'يلزم ترقية الحساب', 'ar', 'dashboard'),
('upgrade_modal_desc', 'لقد وصلت للحد الأقصى من أشجار العائلة في باقتك الحالية', 'ar', 'dashboard'),
('view_plans', 'عرض الباقات', 'ar', 'dashboard'),
('delete_confirmation', 'تأكيد الحذف', 'ar', 'dashboard'),
('delete_tree_warning', 'لتأكيد الحذف، يرجى كتابة اسم الشجرة كما هو موضح تماماً', 'ar', 'dashboard'),
('type_tree_name', 'اكتب اسم الشجرة للتأكيد', 'ar', 'dashboard'),
('confirm_delete', 'تأكيد الحذف', 'ar', 'dashboard'),
('cancel', 'إلغاء', 'ar', 'dashboard'),
('data_loading_error', 'خطأ في تحميل البيانات', 'ar', 'dashboard'),
('delete_confirmation_error', 'خطأ في التأكيد', 'ar', 'dashboard'),
('tree_name_validation', 'يجب كتابة اسم الشجرة بشكل صحيح للتأكيد', 'ar', 'dashboard'),
('delete_error', 'خطأ في الحذف', 'ar', 'dashboard'),
('delete_success', 'تم الحذف بنجاح', 'ar', 'dashboard'),
('tree_deleted_success', 'تم حذف شجرة العائلة بنجاح', 'ar', 'dashboard'),

-- Family Builder translations - English
('family_overview', 'Family Overview', 'en', 'family_builder'),
('add_member', 'Add Member', 'en', 'family_builder'),
('search_members', 'Search members...', 'en', 'family_builder'),
('generation', 'Generation', 'en', 'family_builder'),
('generations', 'Generations', 'en', 'family_builder'),
('total_members', 'Total Members', 'en', 'family_builder'),
('marriages', 'Marriages', 'en', 'family_builder'),
('view_all_members', 'View All Members', 'en', 'family_builder'),
('blood_relations_only', 'Blood Relations Only', 'en', 'family_builder'),
('non_family_members', 'Non-Family Members', 'en', 'family_builder'),
('wives_only', 'Wives Only', 'en', 'family_builder'),
('husbands_only', 'Husbands Only', 'en', 'family_builder'),
('blood_with_female_children', 'Blood Relations & Female Children', 'en', 'family_builder'),
('no_members_found', 'No members found', 'en', 'family_builder'),
('no_members_desc', 'Start building your family tree by adding the first member', 'en', 'family_builder'),
('member_details', 'Member Details', 'en', 'family_builder'),
('member_name', 'Member Name', 'en', 'family_builder'),
('relationship', 'Relationship', 'en', 'family_builder'),
('gender', 'Gender', 'en', 'family_builder'),
('male', 'Male', 'en', 'family_builder'),
('female', 'Female', 'en', 'family_builder'),
('birth_date', 'Birth Date', 'en', 'family_builder'),
('is_alive', 'Is Alive', 'en', 'family_builder'),
('death_date', 'Death Date', 'en', 'family_builder'),
('biography', 'Biography', 'en', 'family_builder'),
('save_member', 'Save Member', 'en', 'family_builder'),
('edit_member', 'Edit Member', 'en', 'family_builder'),
('delete_member', 'Delete Member', 'en', 'family_builder'),

-- Family Builder translations - Arabic  
('family_overview', 'نظرة عامة على العائلة', 'ar', 'family_builder'),
('add_member', 'إضافة عضو', 'ar', 'family_builder'),
('search_members', 'البحث عن الأعضاء...', 'ar', 'family_builder'),
('generation', 'جيل', 'ar', 'family_builder'),
('generations', 'أجيال', 'ar', 'family_builder'),
('total_members', 'إجمالي الأعضاء', 'ar', 'family_builder'),
('marriages', 'زيجات', 'ar', 'family_builder'),
('view_all_members', 'عرض جميع الأعضاء', 'ar', 'family_builder'),
('blood_relations_only', 'عرض الأقارب بالدم (نفس العائلة)', 'ar', 'family_builder'),
('non_family_members', 'عرض جميع الأفراد خارج العائلة الأصلية', 'ar', 'family_builder'),
('wives_only', 'عرض جميع الزوجات', 'ar', 'family_builder'),
('husbands_only', 'عرض جميع الأزواج', 'ar', 'family_builder'),
('blood_with_female_children', 'الأقارب بالدم وأطفال الإناث من نفس عائلة الأب', 'ar', 'family_builder'),
('no_members_found', 'لم يتم العثور على أعضاء', 'ar', 'family_builder'),
('no_members_desc', 'ابدأ ببناء شجرة عائلتك بإضافة العضو الأول', 'ar', 'family_builder'),
('member_details', 'تفاصيل العضو', 'ar', 'family_builder'),
('member_name', 'اسم العضو', 'ar', 'family_builder'),
('relationship', 'صلة القرابة', 'ar', 'family_builder'),
('gender', 'الجنس', 'ar', 'family_builder'),
('male', 'ذكر', 'ar', 'family_builder'),
('female', 'أنثى', 'ar', 'family_builder'),
('birth_date', 'تاريخ الميلاد', 'ar', 'family_builder'),
('is_alive', 'على قيد الحياة', 'ar', 'family_builder'),
('death_date', 'تاريخ الوفاة', 'ar', 'family_builder'),
('biography', 'السيرة الذاتية', 'ar', 'family_builder'),
('save_member', 'حفظ العضو', 'ar', 'family_builder'),
('edit_member', 'تعديل العضو', 'ar', 'family_builder'),
('delete_member', 'حذف العضو', 'ar', 'family_builder'),

-- Auth page translations - English
('welcome_to', 'Welcome to', 'en', 'auth'),
('my_tree', 'My Tree', 'en', 'auth'),
('exceptional_journey', 'Start your exceptional journey in discovering your roots and building a luxurious digital legacy', 'en', 'auth'),
('best_arabic_platform', 'with the best Arabic platform for creating family trees', 'en', 'auth'),
('distinguished_families', 'Distinguished Families', 'en', 'auth'),
('preserved_individuals', 'Preserved Individuals', 'en', 'auth'),
('high_security', 'High Security', 'en', 'auth'),
('luxury_design', 'Luxury Design', 'en', 'auth'),
('high_quality', 'High Quality', 'en', 'auth'),
('premium_experience', 'Premium Experience', 'en', 'auth'),
('discover_roots', 'Discover your roots with the best platform', 'en', 'auth'),
('sign_in', 'Sign In', 'en', 'auth'),
('create_account', 'Create Account', 'en', 'auth'),
('email_address', 'Email Address', 'en', 'auth'),
('password', 'Password', 'en', 'auth'),
('full_name', 'Full Name', 'en', 'auth'),
('phone_number', 'Phone Number', 'en', 'auth'),
('verification_code', 'Verification Code', 'en', 'auth'),
('enter_verification_code', 'Enter the verification code sent to your email', 'en', 'auth'),
('verify_account', 'Verify Account', 'en', 'auth'),
('resend_code', 'Resend Code', 'en', 'auth'),
('back_to_register', 'Back to Registration', 'en', 'auth'),
('sign_in_google', 'Sign in with Google', 'en', 'auth'),
('already_have_account', 'Already have an account?', 'en', 'auth'),
('no_account', 'Don\'t have an account?', 'en', 'auth'),
('register_now', 'Register Now', 'en', 'auth'),
('sign_in_now', 'Sign In Now', 'en', 'auth'),
('home_page', 'Home Page', 'en', 'auth'),

-- Auth page translations - Arabic
('welcome_to', 'مرحباً بك في', 'ar', 'auth'),
('my_tree', 'شجرتي', 'ar', 'auth'),
('exceptional_journey', 'ابدأ رحلتك الاستثنائية في اكتشاف جذورك وبناء إرث رقمي فاخر', 'ar', 'auth'),
('best_arabic_platform', 'مع أفضل منصة عربية لإنشاء أشجار العائلة', 'ar', 'auth'),
('distinguished_families', '+1000 عائلة مميزة', 'ar', 'auth'),
('preserved_individuals', '+50k فرد محفوظ', 'ar', 'auth'),
('high_security', '100% آمان عالي', 'ar', 'auth'),
('luxury_design', 'تصميم فاخر', 'ar', 'auth'),
('high_quality', 'جودة عالية', 'ar', 'auth'),
('premium_experience', 'تجربة مميزة', 'ar', 'auth'),
('discover_roots', 'اكتشف جذورك مع أفضل منصة', 'ar', 'auth'),
('sign_in', 'تسجيل الدخول', 'ar', 'auth'),
('create_account', 'إنشاء حساب', 'ar', 'auth'),
('email_address', 'البريد الإلكتروني', 'ar', 'auth'),
('password', 'كلمة المرور', 'ar', 'auth'),
('full_name', 'الاسم الكامل', 'ar', 'auth'),
('phone_number', 'رقم الهاتف', 'ar', 'auth'),
('verification_code', 'رمز التحقق', 'ar', 'auth'),
('enter_verification_code', 'أدخل رمز التحقق المرسل إلى بريدك الإلكتروني', 'ar', 'auth'),
('verify_account', 'تحقق من الحساب', 'ar', 'auth'),
('resend_code', 'إعادة إرسال الرمز', 'ar', 'auth'),
('back_to_register', 'العودة للتسجيل', 'ar', 'auth'),
('sign_in_google', 'الدخول بـ Google', 'ar', 'auth'),
('already_have_account', 'لديك حساب بالفعل؟', 'ar', 'auth'),
('no_account', 'ليس لديك حساب؟', 'ar', 'auth'),
('register_now', 'سجل الآن', 'ar', 'auth'),
('sign_in_now', 'سجل دخولك الآن', 'ar', 'auth'),
('home_page', 'الصفحة الرئيسية', 'ar', 'auth')

ON CONFLICT (language_code, key) DO UPDATE SET
  value = EXCLUDED.value,
  category = EXCLUDED.category,
  updated_at = now();