INSERT INTO translations (key, language_code, value, category) VALUES
('timeline.born_event', 'ar', 'الميلاد', 'timeline'),
('timeline.born_event', 'en', 'Born', 'timeline'),
('timeline.birth_description', 'ar', 'بداية رحلة حياة وفصل جديد في تاريخ العائلة.', 'timeline'),
('timeline.birth_description', 'en', 'The beginning of a life journey and the start of a new chapter in the family history.', 'timeline'),
('timeline.marriage_with', 'ar', 'الزواج من', 'timeline'),
('timeline.marriage_with', 'en', 'Union with', 'timeline'),
('timeline.marriage_description', 'ar', 'رابطة عززت أواصر العائلة واستمرت في بناء الإرث.', 'timeline'),
('timeline.marriage_description', 'en', 'A union that strengthened the family bonds and continued the legacy.', 'timeline'),
('timeline.family_growth', 'ar', 'أساس الإرث', 'timeline'),
('timeline.family_growth', 'en', 'The Foundation of Legacy', 'timeline'),
('timeline.welcomed', 'ar', 'رُزق بـ', 'timeline'),
('timeline.welcomed', 'en', 'Welcomed', 'timeline'),
('timeline.sons', 'ar', 'أبناء', 'timeline'),
('timeline.sons', 'en', 'sons', 'timeline'),
('timeline.daughters', 'ar', 'بنات', 'timeline'),
('timeline.daughters', 'en', 'daughters', 'timeline'),
('timeline.passing', 'ar', 'حياة اختُتمت بسلام', 'timeline'),
('timeline.passing', 'en', 'A Peacefully Concluded Life', 'timeline'),
('timeline.passed_at_age', 'ar', 'توفي عن عمر يناهز', 'timeline'),
('timeline.passed_at_age', 'en', 'Passed away at age', 'timeline'),
('timeline.remembered', 'ar', 'يُذكر كركيزة للعائلة يستمر إرثها.', 'timeline'),
('timeline.remembered', 'en', 'Remembered as a pillar of the family whose legacy continues.', 'timeline'),
('timeline.life_journey_of', 'ar', 'مسيرة حياة', 'timeline'),
('timeline.life_journey_of', 'en', 'The Life Journey of', 'timeline'),
('timeline.chronological_history', 'ar', 'تاريخ زمني للقيادة والإرث', 'timeline'),
('timeline.chronological_history', 'en', 'A Chronological History of Leadership and Legacy', 'timeline'),
('timeline.no_events', 'ar', 'لا توجد أحداث زمنية', 'timeline'),
('timeline.no_events', 'en', 'No Timeline Events', 'timeline'),
('timeline.add_dates_hint', 'ar', 'أضف تواريخ الميلاد والوفاة لعرض الجدول الزمني.', 'timeline'),
('timeline.add_dates_hint', 'en', 'Add birth and death dates to see the timeline.', 'timeline')
ON CONFLICT (key, language_code) DO UPDATE SET value = EXCLUDED.value;