INSERT INTO translations (key, value, language_code, category) VALUES
('activity.member_added', 'تمت إضافة', 'ar', 'activity'),
('activity.member_updated', 'تم تعديل', 'ar', 'activity'),
('activity.member_deleted', 'تم حذف', 'ar', 'activity'),
('activity.photo_uploaded', 'تم رفع صورة', 'ar', 'activity'),
('activity.photo_deleted', 'تم حذف صورة', 'ar', 'activity'),
('activity.marriage_added', 'تمت إضافة زواج', 'ar', 'activity'),
('activity.marriage_deleted', 'تم حذف زواج', 'ar', 'activity'),
('activity.settings_changed', 'تم تغيير الإعدادات', 'ar', 'activity'),
('activity.collaborator_invited', 'تمت دعوة متعاون', 'ar', 'activity'),
('activity.by', 'بواسطة', 'ar', 'activity'),
('activity.member_added', 'Added', 'en', 'activity'),
('activity.member_updated', 'Updated', 'en', 'activity'),
('activity.member_deleted', 'Deleted', 'en', 'activity'),
('activity.photo_uploaded', 'Photo uploaded for', 'en', 'activity'),
('activity.photo_deleted', 'Photo deleted for', 'en', 'activity'),
('activity.marriage_added', 'Marriage added', 'en', 'activity'),
('activity.marriage_deleted', 'Marriage deleted', 'en', 'activity'),
('activity.settings_changed', 'Settings changed', 'en', 'activity'),
('activity.collaborator_invited', 'Collaborator invited', 'en', 'activity'),
('activity.by', 'by', 'en', 'activity');