
INSERT INTO translations (key, value, language_code, category) VALUES
-- Gallery keys
('gallery.quick_upload', 'رفع سريع', 'ar', 'gallery'),
('gallery.quick_upload', 'Quick Upload', 'en', 'gallery'),
('gallery.premium_feature', 'ميزة مميزة', 'ar', 'gallery'),
('gallery.premium_feature', 'Premium Feature', 'en', 'gallery'),
('gallery.upgrade_to_upload', 'قم بترقية باقتك لرفع الصور', 'ar', 'gallery'),
('gallery.upgrade_to_upload', 'Upgrade your plan to upload photos', 'en', 'gallery'),
('gallery.drop_here', 'أسقط الذكريات هنا', 'ar', 'gallery'),
('gallery.drop_here', 'Drop memories here', 'en', 'gallery'),
('gallery.file_format_hint', 'PNG, JPG حتى 10MB', 'ar', 'gallery'),
('gallery.file_format_hint', 'PNG, JPG up to 10MB', 'en', 'gallery'),
('gallery.no_memories_title', 'لا توجد ذكريات بعد', 'ar', 'gallery'),
('gallery.no_memories_title', 'No memories yet', 'en', 'gallery'),
('gallery.no_memories_desc', 'ابدأ بتوثيق ذكريات عائلتك الثمينة', 'ar', 'gallery'),
('gallery.no_memories_desc', 'Start documenting your precious family memories', 'en', 'gallery'),
('gallery.upload_first', 'ارفع أول صورة', 'ar', 'gallery'),
('gallery.upload_first', 'Upload your first photo', 'en', 'gallery'),
('gallery.memories_count', 'ذكرى', 'ar', 'gallery'),
('gallery.memories_count', 'memories', 'en', 'gallery'),
('gallery.view_all', 'عرض الكل', 'ar', 'gallery'),
('gallery.view_all', 'View All', 'en', 'gallery'),
('gallery.delete_confirm', 'هل أنت متأكد من حذف هذه الذكرى؟', 'ar', 'gallery'),
('gallery.delete_confirm', 'Are you sure you want to delete this memory?', 'en', 'gallery'),
('gallery.deleting', 'جاري الحذف...', 'ar', 'gallery'),
('gallery.deleting', 'Deleting...', 'en', 'gallery'),
('gallery.deleted', 'تم الحذف', 'ar', 'gallery'),
('gallery.deleted', 'Deleted', 'en', 'gallery'),
('gallery.delete_success', 'تم حذف الذكرى بنجاح', 'ar', 'gallery'),
('gallery.delete_success', 'Memory deleted successfully', 'en', 'gallery'),
('gallery.upload_success', 'تم رفع الصورة', 'ar', 'gallery'),
('gallery.upload_success', 'Photo uploaded', 'en', 'gallery'),
('gallery.upload_success_desc', 'تمت إضافة الذكرى بنجاح', 'ar', 'gallery'),
('gallery.upload_success_desc', 'Memory added successfully', 'en', 'gallery'),
('gallery.save', 'حفظ', 'ar', 'gallery'),
('gallery.save', 'Save', 'en', 'gallery'),
('gallery.caption_placeholder', 'أضف وصفاً للصورة...', 'ar', 'gallery'),
('gallery.caption_placeholder', 'Add a caption...', 'en', 'gallery'),
('gallery.photo_date', 'تاريخ الصورة', 'ar', 'gallery'),
('gallery.photo_date', 'Photo date', 'en', 'gallery'),
('gallery.upgrade_plan', 'ترقية الباقة', 'ar', 'gallery'),
('gallery.upgrade_plan', 'Upgrade Plan', 'en', 'gallery'),

-- Stitch/Dashboard keys
('stitch.welcome_back', 'مرحباً بعودتك', 'ar', 'stitch'),
('stitch.welcome_back', 'Welcome back', 'en', 'stitch'),
('stitch.upcoming_birthdays', 'أعياد الميلاد القادمة', 'ar', 'stitch'),
('stitch.upcoming_birthdays', 'Upcoming Birthdays', 'en', 'stitch'),
('stitch.no_upcoming', 'لا توجد أعياد ميلاد قادمة', 'ar', 'stitch'),
('stitch.no_upcoming', 'No upcoming birthdays', 'en', 'stitch'),
('stitch.days_left', 'يوم متبقي', 'ar', 'stitch'),
('stitch.days_left', 'days left', 'en', 'stitch'),
('stitch.total_members', 'إجمالي الأعضاء', 'ar', 'stitch'),
('stitch.total_members', 'Total Members', 'en', 'stitch'),
('stitch.alive_members', 'الأعضاء الأحياء', 'ar', 'stitch'),
('stitch.alive_members', 'Alive Members', 'en', 'stitch'),
('stitch.deceased_members', 'الأعضاء المتوفين', 'ar', 'stitch'),
('stitch.deceased_members', 'Deceased Members', 'en', 'stitch'),
('stitch.male_count', 'ذكور', 'ar', 'stitch'),
('stitch.male_count', 'Males', 'en', 'stitch'),
('stitch.female_count', 'إناث', 'ar', 'stitch'),
('stitch.female_count', 'Females', 'en', 'stitch'),
('stitch.recent_activity', 'النشاط الأخير', 'ar', 'stitch'),
('stitch.recent_activity', 'Recent Activity', 'en', 'stitch'),
('stitch.no_activity', 'لا يوجد نشاط حتى الآن', 'ar', 'stitch'),
('stitch.no_activity', 'No activity yet', 'en', 'stitch'),
('stitch.search_placeholder', 'ابحث عن أعضاء...', 'ar', 'stitch'),
('stitch.search_placeholder', 'Search members...', 'en', 'stitch'),
('stitch.desktop_optimized', 'هذه الصفحة مُحسّنة للاستخدام على سطح المكتب', 'ar', 'stitch'),
('stitch.desktop_optimized', 'This page is optimized for desktop', 'en', 'stitch'),

-- Profile/Member keys
('profile.status', 'الحالة', 'ar', 'profile'),
('profile.status', 'Status', 'en', 'profile'),
('profile.delete_warning_title', 'تحذير حذف العضو', 'ar', 'profile'),
('profile.delete_warning_title', 'Delete Member Warning', 'en', 'profile'),
('profile.delete_warning_subtitle', 'أنت على وشك إزالة هذا الفرد نهائياً من الشجرة', 'ar', 'profile'),
('profile.delete_warning_subtitle', 'You are about to permanently remove this member from the tree', 'en', 'profile'),
('profile.selected_member', 'العضو المختار', 'ar', 'profile'),
('profile.selected_member', 'Selected Member', 'en', 'profile'),
('profile.affected_data', 'البيانات المتأثرة بالحذف', 'ar', 'profile'),
('profile.affected_data', 'Data Affected by Deletion', 'en', 'profile'),
('profile.spouses_label', 'الأزواج', 'ar', 'profile'),
('profile.spouses_label', 'Spouses', 'en', 'profile'),
('profile.children_label', 'الأطفال', 'ar', 'profile'),
('profile.children_label', 'Children', 'en', 'profile'),
('profile.relationships_label', 'العلاقات', 'ar', 'profile'),
('profile.relationships_label', 'Relationships', 'en', 'profile'),
('profile.permanent_action', 'إجراء نهائي', 'ar', 'profile'),
('profile.permanent_action', 'Permanent Action', 'en', 'profile'),
('profile.delete_permanent_warning', 'هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع البيانات المتعلقة والروابط العائلية لهذا العضو بشكل قطعي.', 'ar', 'profile'),
('profile.delete_permanent_warning', 'This action cannot be undone. All related data and family links for this member will be permanently deleted.', 'en', 'profile'),
('profile.deletion_success', 'تم الحذف بنجاح', 'ar', 'profile'),
('profile.deletion_success', 'Deleted Successfully', 'en', 'profile'),
('profile.member_deleted', 'تم حذف العضو بنجاح', 'ar', 'profile'),
('profile.member_deleted', 'Member has been deleted successfully', 'en', 'profile'),
('profile.delete_failed', 'فشل في حذف العضو', 'ar', 'profile'),
('profile.delete_failed', 'Failed to delete member', 'en', 'profile'),
('profile.confirm_delete', 'تأكيد الحذف', 'ar', 'profile'),
('profile.confirm_delete', 'Confirm Delete', 'en', 'profile'),
('profile.deleting', 'جاري الحذف...', 'ar', 'profile'),
('profile.deleting', 'Deleting...', 'en', 'profile'),
('profile.edit_profile', 'تعديل الملف الشخصي', 'ar', 'profile'),
('profile.edit_profile', 'Edit Profile', 'en', 'profile'),
('profile.save_changes', 'حفظ التغييرات', 'ar', 'profile'),
('profile.save_changes', 'Save Changes', 'en', 'profile'),
('profile.saving', 'جاري الحفظ...', 'ar', 'profile'),
('profile.saving', 'Saving...', 'en', 'profile'),

-- Member keys
('member.founder', 'المؤسس', 'ar', 'member'),
('member.founder', 'Founder', 'en', 'member'),
('member.biography_placeholder', 'اكتب سيرة ذاتية مختصرة...', 'ar', 'member'),
('member.biography_placeholder', 'Write a short biography...', 'en', 'member'),
('member.add_child', 'إضافة ابن/ابنة', 'ar', 'member'),
('member.add_child', 'Add Child', 'en', 'member'),
('member.add_spouse', 'إضافة زوج/زوجة', 'ar', 'member'),
('member.add_spouse', 'Add Spouse', 'en', 'member'),
('member.delete_member', 'حذف العضو', 'ar', 'member'),
('member.delete_member', 'Delete Member', 'en', 'member'),
('member.alive', 'على قيد الحياة', 'ar', 'member'),
('member.alive', 'Alive', 'en', 'member'),
('member.deceased', 'متوفى', 'ar', 'member'),
('member.deceased', 'Deceased', 'en', 'member'),
('member.birth_date', 'تاريخ الميلاد', 'ar', 'member'),
('member.birth_date', 'Birth Date', 'en', 'member'),
('member.death_date', 'تاريخ الوفاة', 'ar', 'member'),
('member.death_date', 'Death Date', 'en', 'member'),
('member.gender', 'الجنس', 'ar', 'member'),
('member.gender', 'Gender', 'en', 'member'),
('member.male', 'ذكر', 'ar', 'member'),
('member.male', 'Male', 'en', 'member'),
('member.female', 'أنثى', 'ar', 'member'),
('member.female', 'Female', 'en', 'member'),

-- Tree view keys
('tree_view.multiple_spouses', 'أزواج متعددين', 'ar', 'tree_view'),
('tree_view.multiple_spouses', 'Multiple Spouses', 'en', 'tree_view'),
('tree_view.zoom_in', 'تكبير', 'ar', 'tree_view'),
('tree_view.zoom_in', 'Zoom In', 'en', 'tree_view'),
('tree_view.zoom_out', 'تصغير', 'ar', 'tree_view'),
('tree_view.zoom_out', 'Zoom Out', 'en', 'tree_view'),
('tree_view.fit_view', 'ملائمة العرض', 'ar', 'tree_view'),
('tree_view.fit_view', 'Fit View', 'en', 'tree_view'),

-- Common keys
('common.error', 'خطأ', 'ar', 'common'),
('common.error', 'Error', 'en', 'common'),
('common.loading', 'جاري التحميل...', 'ar', 'common'),
('common.loading', 'Loading...', 'en', 'common'),
('common.cancel', 'إلغاء', 'ar', 'common'),
('common.cancel', 'Cancel', 'en', 'common'),
('common.save', 'حفظ', 'ar', 'common'),
('common.save', 'Save', 'en', 'common'),
('common.delete', 'حذف', 'ar', 'common'),
('common.delete', 'Delete', 'en', 'common'),
('common.close', 'إغلاق', 'ar', 'common'),
('common.close', 'Close', 'en', 'common'),

-- Suggestions additional
('suggestions.no_pending', 'لا توجد اقتراحات بانتظار المراجعة', 'ar', 'suggestions'),
('suggestions.no_pending', 'No pending suggestions', 'en', 'suggestions'),

-- Stats additional
('stats.completeness_desc', 'نسبة اكتمال البيانات من صور واسم وتاريخ ميلاد ووصف', 'ar', 'stats'),
('stats.completeness_desc', 'Data completeness from photos, name, birth date, and bio', 'en', 'stats'),
('stats.generations', 'الأجيال', 'ar', 'stats'),
('stats.generations', 'Generations', 'en', 'stats'),

-- Time keys
('time.just_now', 'الآن', 'ar', 'time'),
('time.just_now', 'Just now', 'en', 'time'),
('time.ago', 'منذ', 'ar', 'time'),
('time.ago', 'ago', 'en', 'time'),
('time.minutes', 'دقيقة', 'ar', 'time'),
('time.minutes', 'minutes', 'en', 'time'),
('time.hours', 'ساعة', 'ar', 'time'),
('time.hours', 'hours', 'en', 'time'),
('time.days', 'يوم', 'ar', 'time'),
('time.days', 'days', 'en', 'time')
ON CONFLICT (key, language_code) DO NOTHING;
