
INSERT INTO translations (key, language_code, value, category) VALUES
-- Account
('account.profile_info', 'ar', 'المعلومات الشخصية', 'account'),
('account.profile_info', 'en', 'Profile Information', 'account'),
('account.subscriptions_billing', 'ar', 'الاشتراكات والفوترة', 'account'),
('account.subscriptions_billing', 'en', 'Subscriptions & Billing', 'account'),
('account.security_access', 'ar', 'الأمان والوصول', 'account'),
('account.security_access', 'en', 'Security & Access', 'account'),
('account.settings', 'ar', 'إعدادات الحساب', 'account'),
('account.settings', 'en', 'Account Settings', 'account'),
('account.security_desc', 'ar', 'إدارة كلمة المرور وإعدادات أمان حسابك.', 'account'),
('account.security_desc', 'en', 'Manage your password and account security settings.', 'account'),
('account.account_stats', 'ar', 'إحصائيات الحساب', 'account'),
('account.account_stats', 'en', 'Account Stats', 'account'),
('account.security_tips', 'ar', 'نصائح أمنية', 'account'),
('account.security_tips', 'en', 'Security Tips', 'account'),
('account.stronger_passwords', 'ar', 'كلمات مرور أقوى', 'account'),
('account.stronger_passwords', 'en', 'Stronger Passwords', 'account'),
('account.stronger_passwords_desc', 'ar', 'استخدم مزيجاً من الأحرف والأرقام والرموز لأمان أفضل.', 'account'),
('account.stronger_passwords_desc', 'en', 'Use a mix of letters, numbers, and symbols for better security.', 'account'),
('account.need_help', 'ar', 'تحتاج مساعدة؟', 'account'),
('account.need_help', 'en', 'Need help?', 'account'),
('account.support_desc', 'ar', 'فريق الدعم متاح على مدار الساعة للاستفسارات المتعلقة بالحساب.', 'account'),
('account.support_desc', 'en', 'Our support team is available 24/7 for account related inquiries.', 'account'),
('account.contact_support', 'ar', 'تواصل مع الدعم', 'account'),
('account.contact_support', 'en', 'Contact Support', 'account'),
('account.desktop_message', 'ar', 'إعدادات شجرتي تعمل بشكل أفضل على الكمبيوتر أو الجهاز اللوحي.', 'account'),
('account.desktop_message', 'en', 'Shjrti Settings is best experienced on a desktop or tablet.', 'account'),
('account.continue_anyway', 'ar', 'المتابعة على أي حال', 'account'),
('account.continue_anyway', 'en', 'Continue Anyway', 'account'),

-- Profile
('profile.saving', 'ar', 'جاري الحفظ...', 'profile'),
('profile.saving', 'en', 'Saving...', 'profile'),
('profile.update_password', 'ar', 'تحديث كلمة المرور', 'profile'),
('profile.update_password', 'en', 'Update Password', 'profile'),
('profile.danger_zone_desc', 'ar', 'حذف نهائي لجميع بيانات عائلتك وأشجارك.', 'profile'),
('profile.danger_zone_desc', 'en', 'Permanent deletion of all your family data and trees.', 'profile'),
('profile.delete_account', 'ar', 'حذف الحساب', 'profile'),
('profile.delete_account', 'en', 'Delete Account', 'profile'),
('profile.passwords_mismatch', 'ar', 'كلمات المرور غير متطابقة', 'profile'),
('profile.passwords_mismatch', 'en', 'Passwords do not match', 'profile'),
('profile.success', 'ar', 'تم بنجاح', 'profile'),
('profile.success', 'en', 'Success', 'profile'),
('profile.password_changed', 'ar', 'تم تغيير كلمة المرور بنجاح', 'profile'),
('profile.password_changed', 'en', 'Password changed successfully', 'profile'),
('profile.unexpected_error', 'ar', 'حدث خطأ غير متوقع', 'profile'),
('profile.unexpected_error', 'en', 'An unexpected error occurred', 'profile'),

-- Billing
('billing.free_plan', 'ar', 'الباقة المجانية', 'billing'),
('billing.free_plan', 'en', 'Free Plan', 'billing'),
('billing.choose_plan', 'ar', 'اختر باقتك', 'billing'),
('billing.choose_plan', 'en', 'Choose Your Plan', 'billing'),
('billing.choose_plan_desc', 'ar', 'اختر الباقة التي تناسب احتياجات تاريخ عائلتك.', 'billing'),
('billing.choose_plan_desc', 'en', 'Pick the plan that best fits your family history needs.', 'billing'),
('billing.most_popular', 'ar', 'الأكثر شعبية', 'billing'),
('billing.most_popular', 'en', 'Most Popular', 'billing'),
('billing.free_forever', 'ar', 'مجانية للأبد', 'billing'),
('billing.free_forever', 'en', 'Free for Life', 'billing'),
('billing.year', 'ar', 'سنة', 'billing'),
('billing.year', 'en', 'Year', 'billing'),
('billing.approx', 'ar', 'تقريباً', 'billing'),
('billing.approx', 'en', 'Approx.', 'billing'),
('billing.family_trees', 'ar', 'أشجار عائلية', 'billing'),
('billing.family_trees', 'en', 'Family Trees', 'billing'),
('billing.up_to', 'ar', 'حتى', 'billing'),
('billing.up_to', 'en', 'Up to', 'billing'),
('billing.members', 'ar', 'أعضاء', 'billing'),
('billing.members', 'en', 'Members', 'billing'),
('billing.active_plan', 'ar', 'الباقة الحالية', 'billing'),
('billing.active_plan', 'en', 'Active Plan', 'billing'),
('billing.processing', 'ar', 'جاري المعالجة...', 'billing'),
('billing.processing', 'en', 'Processing...', 'billing'),
('billing.subscribe_now', 'ar', 'اشترك الآن', 'billing'),
('billing.subscribe_now', 'en', 'Subscribe Now', 'billing'),
('billing.invoice_history', 'ar', 'سجل الفواتير', 'billing'),
('billing.invoice_history', 'en', 'Invoice History', 'billing'),
('billing.invoice_history_desc', 'ar', 'عرض وتحميل سجل الفوترة الخاص بك', 'billing'),
('billing.invoice_history_desc', 'en', 'View and download your billing history', 'billing'),
('billing.loading_invoices', 'ar', 'جاري تحميل الفواتير...', 'billing'),
('billing.loading_invoices', 'en', 'Loading invoices...', 'billing'),
('billing.no_invoices', 'ar', 'لا توجد فواتير بعد', 'billing'),
('billing.no_invoices', 'en', 'No invoices yet', 'billing'),
('billing.invoices_appear', 'ar', 'ستظهر فواتيرك هنا بعد الترقية لباقة مدفوعة', 'billing'),
('billing.invoices_appear', 'en', 'Your invoices will appear here after upgrading to a paid plan', 'billing'),
('billing.paid', 'ar', 'مدفوعة', 'billing'),
('billing.paid', 'en', 'Paid', 'billing'),
('billing.pending', 'ar', 'بانتظار الدفع', 'billing'),
('billing.pending', 'en', 'Pending Payment', 'billing'),
('billing.cancelled_status', 'ar', 'ملغاة', 'billing'),
('billing.cancelled_status', 'en', 'Cancelled', 'billing'),
('billing.click_to_pay', 'ar', 'اضغط للدفع', 'billing'),
('billing.click_to_pay', 'en', 'Click to pay', 'billing'),
('billing.pay_now', 'ar', 'ادفع الآن', 'billing'),
('billing.pay_now', 'en', 'Pay Now', 'billing'),
('billing.download', 'ar', 'تحميل', 'billing'),
('billing.download', 'en', 'Download', 'billing'),
('billing.plan', 'ar', 'الباقة', 'billing'),
('billing.plan', 'en', 'Plan', 'billing'),
('billing.unknown', 'ar', 'غير معروف', 'billing'),
('billing.unknown', 'en', 'Unknown', 'billing'),
('billing.your_current_plan', 'ar', 'باقتك الحالية', 'billing'),
('billing.your_current_plan', 'en', 'Your Current Plan', 'billing'),
('billing.paid_plan', 'ar', 'باقة مدفوعة', 'billing'),
('billing.paid_plan', 'en', 'Paid Plan', 'billing'),
('billing.active', 'ar', 'نشطة', 'billing'),
('billing.active', 'en', 'Active', 'billing'),
('billing.expired', 'ar', 'منتهية', 'billing'),
('billing.expired', 'en', 'Expired', 'billing'),
('billing.max_trees', 'ar', 'الحد الأقصى للأشجار', 'billing'),
('billing.max_trees', 'en', 'Max Trees', 'billing'),
('billing.member_limit', 'ar', 'حد الأعضاء', 'billing'),
('billing.member_limit', 'en', 'Member Limit', 'billing'),
('billing.renewal_date', 'ar', 'تاريخ التجديد', 'billing'),
('billing.renewal_date', 'en', 'Renewal Date', 'billing'),
('billing.not_specified', 'ar', 'غير محدد', 'billing'),
('billing.not_specified', 'en', 'N/A', 'billing'),
('billing.none', 'ar', 'لا يوجد', 'billing'),
('billing.none', 'en', 'None', 'billing'),
('billing.plan_usage', 'ar', 'استخدام الباقة', 'billing'),
('billing.plan_usage', 'en', 'Plan Usage', 'billing'),
('billing.of_limit_used', 'ar', 'من حد باقتك الحالية مستخدم', 'billing'),
('billing.of_limit_used', 'en', 'of your current plan limit used', 'billing'),
('billing.cancelled', 'ar', 'تم الإلغاء', 'billing'),
('billing.cancelled', 'en', 'Cancelled', 'billing'),
('billing.scheduled_change_cancelled', 'ar', 'تم إلغاء التغيير المجدول. ستبقى على باقتك الحالية.', 'billing'),
('billing.scheduled_change_cancelled', 'en', 'Scheduled change has been cancelled. You will stay on your current plan.', 'billing'),
('billing.cancel_error', 'ar', 'حدث خطأ أثناء إلغاء التغيير المجدول', 'billing'),
('billing.cancel_error', 'en', 'An error occurred while cancelling the scheduled change', 'billing'),
('billing.warning', 'ar', 'تحذير', 'billing'),
('billing.warning', 'en', 'Warning', 'billing'),
('billing.important_notice', 'ar', 'ملاحظة مهمة', 'billing'),
('billing.important_notice', 'en', 'Important Notice', 'billing'),
('billing.scheduled', 'ar', 'تمت الجدولة', 'billing'),
('billing.scheduled', 'en', 'Scheduled', 'billing'),
('billing.change_scheduled', 'ar', 'تمت جدولة تغيير الباقة بنجاح.', 'billing'),
('billing.change_scheduled', 'en', 'Package change has been scheduled successfully.', 'billing'),
('billing.free_activated', 'ar', 'تم تفعيل الباقة المجانية', 'billing'),
('billing.free_activated', 'en', 'Free plan activated', 'billing'),
('billing.free_activated_desc', 'ar', 'تم تفعيل الباقة المجانية بنجاح', 'billing'),
('billing.free_activated_desc', 'en', 'Free plan activated successfully', 'billing'),
('billing.payment_error', 'ar', 'خطأ في الدفع', 'billing'),
('billing.payment_error', 'en', 'Payment Error', 'billing'),
('billing.login_to_select', 'ar', 'يرجى تسجيل الدخول أولاً لاختيار باقة', 'billing'),
('billing.login_to_select', 'en', 'Please login first to select a plan', 'billing'),

-- Auth
('auth.login_required', 'ar', 'تسجيل الدخول مطلوب', 'auth'),
('auth.login_required', 'en', 'Login Required', 'auth')

ON CONFLICT (key, language_code) DO NOTHING;
