INSERT INTO translations (key, value, language_code, category) VALUES
('stats.growth_statistics', 'إحصائيات النمو', 'ar', 'stats'),
('stats.growth_statistics', 'Growth Statistics', 'en', 'stats'),
('stats.data_completeness', 'اكتمال البيانات', 'ar', 'stats'),
('stats.data_completeness', 'Data Completeness', 'en', 'stats'),
('stats.uploaded_photos', 'الصور المرفوعة', 'ar', 'stats'),
('stats.uploaded_photos', 'Uploaded Photos', 'en', 'stats'),
('stats.family_distribution', 'توزيع العائلة', 'ar', 'stats'),
('stats.family_distribution', 'Family Distribution', 'en', 'stats'),
('suggestions.pending', 'الاقتراحات المعلقة', 'ar', 'suggestions'),
('suggestions.pending', 'Pending Suggestions', 'en', 'suggestions'),
('suggestions.new', 'جديد', 'ar', 'suggestions'),
('suggestions.new', 'New', 'en', 'suggestions'),
('suggestions.about_member', 'حول العضو', 'ar', 'suggestions'),
('suggestions.about_member', 'About Member', 'en', 'suggestions'),
('suggestions.general', 'اقتراح عام', 'ar', 'suggestions'),
('suggestions.general', 'General Suggestion', 'en', 'suggestions'),
('suggestions.from_label', 'من', 'ar', 'suggestions'),
('suggestions.from_label', 'From', 'en', 'suggestions'),
('suggestions.on_date', 'بتاريخ', 'ar', 'suggestions'),
('suggestions.on_date', 'on', 'en', 'suggestions'),
('suggestions.review_all', 'مراجعة الاقتراحات', 'ar', 'suggestions'),
('suggestions.review_all', 'Review Suggestions', 'en', 'suggestions');