INSERT INTO translations (key, language_code, value, category) VALUES
('dashboard.my_family_trees', 'en', 'My Family Trees', 'dashboard'),
('dashboard.my_family_trees', 'ar', 'أشجار عائلتي', 'dashboard'),
('dashboard.family_trees_subtitle', 'en', 'Curate and maintain your family lineages', 'dashboard'),
('dashboard.family_trees_subtitle', 'ar', 'أنشئ وحافظ على سلالات عائلتك', 'dashboard'),
('dashboard.filter', 'en', 'Filter', 'dashboard'),
('dashboard.filter', 'ar', 'تصفية', 'dashboard'),
('dashboard.active_tree', 'en', 'Active Tree', 'dashboard'),
('dashboard.active_tree', 'ar', 'شجرة نشطة', 'dashboard'),
('dashboard.members', 'en', 'Members', 'dashboard'),
('dashboard.members', 'ar', 'الأعضاء', 'dashboard'),
('dashboard.updated', 'en', 'Updated', 'dashboard'),
('dashboard.updated', 'ar', 'آخر تحديث', 'dashboard'),
('dashboard.not_available', 'en', 'N/A', 'dashboard'),
('dashboard.not_available', 'ar', 'غير متوفر', 'dashboard'),
('dashboard.manage', 'en', 'Manage', 'dashboard'),
('dashboard.manage', 'ar', 'إدارة', 'dashboard'),
('dashboard.create_new_tree', 'en', 'Create New Tree', 'dashboard'),
('dashboard.create_new_tree', 'ar', 'إنشاء شجرة جديدة', 'dashboard'),
('dashboard.create_tree_description', 'en', 'Start a new lineage and begin documenting your heritage.', 'dashboard'),
('dashboard.create_tree_description', 'ar', 'ابدأ سلالة جديدة ووثّق تراثك.', 'dashboard'),
('dashboard.secure_private', 'en', 'Secure & Private', 'dashboard'),
('dashboard.secure_private', 'ar', 'آمن وخاص', 'dashboard'),
('dashboard.secure_private_desc', 'en', 'Your family data is encrypted and only visible to you and your invited members.', 'dashboard'),
('dashboard.secure_private_desc', 'ar', 'بيانات عائلتك مشفّرة ومرئية فقط لك ولأعضائك المدعوين.', 'dashboard'),
('dashboard.build_together', 'en', 'Build Together', 'dashboard'),
('dashboard.build_together', 'ar', 'ابنوا معاً', 'dashboard'),
('dashboard.build_together_desc', 'en', 'Invite siblings and cousins to contribute photos and stories to your shared tree.', 'dashboard'),
('dashboard.build_together_desc', 'ar', 'ادعُ إخوتك وأقاربك للمساهمة بالصور والقصص في شجرتكم المشتركة.', 'dashboard'),
('dashboard.expert_support', 'en', 'Expert Support', 'dashboard'),
('dashboard.expert_support', 'ar', 'دعم متخصص', 'dashboard'),
('dashboard.expert_support_desc', 'en', 'Need help tracing your roots? Our genealogy experts are here to assist you.', 'dashboard'),
('dashboard.expert_support_desc', 'ar', 'تحتاج مساعدة في تتبع جذورك؟ خبراء الأنساب لدينا هنا لمساعدتك.', 'dashboard'),
('dashboard.copyright', 'en', '© 2024 Shjrti Platform', 'dashboard'),
('dashboard.copyright', 'ar', '© 2024 منصة شجرتي', 'dashboard'),
('dashboard.privacy', 'en', 'Privacy', 'dashboard'),
('dashboard.privacy', 'ar', 'الخصوصية', 'dashboard'),
('dashboard.terms', 'en', 'Terms', 'dashboard'),
('dashboard.terms', 'ar', 'الشروط', 'dashboard'),
('dashboard.api_docs', 'en', 'API docs', 'dashboard'),
('dashboard.api_docs', 'ar', 'وثائق API', 'dashboard'),
('dashboard.support', 'en', 'Support', 'dashboard'),
('dashboard.support', 'ar', 'الدعم', 'dashboard')
ON CONFLICT DO NOTHING;