INSERT INTO translations (key, language_code, value, category) VALUES
-- Delete modal
('delete_modal.title', 'ar', 'تحذير: حذف الحساب نهائيًا', 'delete_modal'),
('delete_modal.title', 'en', 'Warning: Permanently Delete Account', 'delete_modal'),
('delete_modal.irreversible', 'ar', 'هذا الإجراء لا يمكن التراجع عنه! سيتم حذف:', 'delete_modal'),
('delete_modal.irreversible', 'en', 'This action cannot be undone! The following will be deleted:', 'delete_modal'),
('delete_modal.family_trees', 'ar', 'شجرة عائلة', 'delete_modal'),
('delete_modal.family_trees', 'en', 'family trees', 'delete_modal'),
('delete_modal.members', 'ar', 'عضو', 'delete_modal'),
('delete_modal.members', 'en', 'members', 'delete_modal'),
('delete_modal.photos_memories', 'ar', 'الصور والذكريات', 'delete_modal'),
('delete_modal.photos_memories', 'en', 'Photos & memories', 'delete_modal'),
('delete_modal.subscriptions_invoices', 'ar', 'الاشتراك والفواتير', 'delete_modal'),
('delete_modal.subscriptions_invoices', 'en', 'Subscriptions & invoices', 'delete_modal'),
('delete_modal.no_recovery', 'ar', 'لا يمكن استرجاع البيانات بعد الحذف!', 'delete_modal'),
('delete_modal.no_recovery', 'en', 'Data cannot be recovered after deletion!', 'delete_modal'),
('delete_modal.type_to_confirm', 'ar', 'اكتب', 'delete_modal'),
('delete_modal.type_to_confirm', 'en', 'Type', 'delete_modal'),
('delete_modal.to_confirm', 'ar', 'للتأكيد:', 'delete_modal'),
('delete_modal.to_confirm', 'en', 'to confirm:', 'delete_modal'),
('delete_modal.cancel', 'ar', 'إلغاء', 'delete_modal'),
('delete_modal.cancel', 'en', 'Cancel', 'delete_modal'),
('delete_modal.delete_permanently', 'ar', 'حذف حسابي نهائيًا', 'delete_modal'),
('delete_modal.delete_permanently', 'en', 'Delete My Account Permanently', 'delete_modal'),
('delete_modal.deleting_account', 'ar', 'جاري حذف الحساب...', 'delete_modal'),
('delete_modal.deleting_account', 'en', 'Deleting account...', 'delete_modal'),
('delete_modal.deleted_success', 'ar', 'تم الحذف بنجاح', 'delete_modal'),
('delete_modal.deleted_success', 'en', 'Deleted Successfully', 'delete_modal'),
('delete_modal.finishing', 'ar', 'جاري الإنهاء...', 'delete_modal'),
('delete_modal.finishing', 'en', 'Finishing...', 'delete_modal'),
('delete_modal.redirecting', 'ar', 'سيتم توجيهك إلى الصفحة الرئيسية الآن...', 'delete_modal'),
('delete_modal.redirecting', 'en', 'You will be redirected to the homepage now...', 'delete_modal'),
('delete_modal.close', 'ar', 'إغلاق', 'delete_modal'),
('delete_modal.close', 'en', 'Close', 'delete_modal'),
('delete_modal.step_trees', 'ar', 'جاري حذف الأشجار والأعضاء...', 'delete_modal'),
('delete_modal.step_trees', 'en', 'Deleting trees and members...', 'delete_modal'),
('delete_modal.step_photos', 'ar', 'جاري حذف الصور والذكريات...', 'delete_modal'),
('delete_modal.step_photos', 'en', 'Deleting photos and memories...', 'delete_modal'),
('delete_modal.step_subscriptions', 'ar', 'جاري حذف الاشتراكات والفواتير...', 'delete_modal'),
('delete_modal.step_subscriptions', 'en', 'Deleting subscriptions and invoices...', 'delete_modal'),
('delete_modal.step_account', 'ar', 'جاري حذف الحساب نهائيًا...', 'delete_modal'),
('delete_modal.step_account', 'en', 'Permanently deleting account...', 'delete_modal'),
('delete_modal.step_done', 'ar', 'تم الحذف بنجاح ✓', 'delete_modal'),
('delete_modal.step_done', 'en', 'Deleted successfully ✓', 'delete_modal')
ON CONFLICT (key, language_code) DO NOTHING;