
-- Insert missing translations for AddMemberForm and SpouseDrawer
INSERT INTO translations (key, language_code, value, category) VALUES
-- member keys
('member.crop_image', 'ar', 'قص الصورة', 'member'),
('member.crop_image', 'en', 'Crop Image', 'member'),
('member.zoom', 'ar', 'تكبير', 'member'),
('member.zoom', 'en', 'Zoom', 'member'),
('member.apply', 'ar', 'تطبيق', 'member'),
('member.apply', 'en', 'Apply', 'member'),
('member.click_to_upload', 'ar', 'اضغط للرفع', 'member'),
('member.click_to_upload', 'en', 'Click to upload', 'member'),
('member.save_changes', 'ar', 'حفظ التعديلات', 'member'),
('member.save_changes', 'en', 'Save Changes', 'member'),
('member.save_member', 'ar', 'حفظ العضو', 'member'),
('member.save_member', 'en', 'Save Member', 'member'),
('member.saving', 'ar', 'جاري الحفظ...', 'member'),
('member.saving', 'en', 'Saving...', 'member'),
('member.spouse', 'ar', 'شريك الحياة', 'member'),
('member.spouse', 'en', 'Spouse', 'member'),
('member.unnamed', 'ar', 'بدون اسم', 'member'),
('member.unnamed', 'en', 'Unnamed', 'member'),
('member.add_wife', 'ar', 'إضافة زوجة', 'member'),
('member.add_wife', 'en', 'Add Wife', 'member'),
('member.add_husband', 'ar', 'إضافة زوج', 'member'),
('member.add_husband', 'en', 'Add Husband', 'member'),
('member.husband_info', 'ar', 'معلومات الزوج', 'member'),
('member.husband_info', 'en', 'Husband Information', 'member'),
('member.wife_info', 'ar', 'معلومات الزوجة', 'member'),
('member.wife_info', 'en', 'Wife Information', 'member'),
('member.edit', 'ar', 'تعديل العضو', 'member'),
('member.edit', 'en', 'Edit Member', 'member'),
('member.edit_desc', 'ar', 'قم بتعديل بيانات العضو', 'member'),
('member.edit_desc', 'en', 'Edit member details', 'member'),
('member.upload_photo_optional', 'ar', 'رفع صورة (اختياري)', 'member'),
('member.upload_photo_optional', 'en', 'Upload Photo (Optional)', 'member'),
('member.click_to_change', 'ar', 'اضغط للتغيير', 'member'),
('member.click_to_change', 'en', 'Click to change', 'member'),
('member.confirm_husband', 'ar', 'تأكيد الزوج', 'member'),
('member.confirm_husband', 'en', 'Confirm Husband', 'member'),
('member.confirm_wife', 'ar', 'تأكيد الزوجة', 'member'),
('member.confirm_wife', 'en', 'Confirm Wife', 'member'),
('member.vitality_status', 'ar', 'حالة الحياة', 'member'),
('member.vitality_status', 'en', 'Vitality Status', 'member'),
('member.living', 'ar', 'على قيد الحياة', 'member'),
('member.living', 'en', 'Living', 'member'),
('member.unknown', 'ar', 'غير معروف', 'member'),
('member.unknown', 'en', 'Unknown', 'member'),
('member.no_marriages', 'ar', 'لا توجد زيجات مسجلة', 'member'),
('member.no_marriages', 'en', 'No marriages registered', 'member'),
('member.parents_locked', 'ar', 'تم اختيار الوالدين تلقائياً', 'member'),
('member.parents_locked', 'en', 'Parents auto-selected', 'member'),
('member.select_parents', 'ar', 'اختر الوالدين', 'member'),
('member.select_parents', 'en', 'Select parents', 'member'),
('member.search_parents', 'ar', 'ابحث عن الوالدين...', 'member'),
('member.search_parents', 'en', 'Search parents...', 'member'),
('member.image_deleted', 'ar', 'تم حذف الصورة', 'member'),
('member.image_deleted', 'en', 'Image deleted', 'member'),
('member.image_deleted_desc', 'ar', 'تم حذف صورة العضو بنجاح', 'member'),
('member.image_deleted_desc', 'en', 'Member image deleted successfully', 'member'),
('member.image_delete_failed', 'ar', 'فشل حذف الصورة', 'member'),
('member.image_delete_failed', 'en', 'Failed to delete image', 'member'),
('member.image_delete_failed_desc', 'ar', 'حدث خطأ أثناء حذف الصورة', 'member'),
('member.image_delete_failed_desc', 'en', 'An error occurred while deleting the image', 'member'),
-- lineage words
('member.son_of', 'ar', 'بن', 'member'),
('member.son_of', 'en', 'son of', 'member'),
('member.daughter_of', 'ar', 'بنت', 'member'),
('member.daughter_of', 'en', 'daughter of', 'member'),
('member.child_of_male', 'ar', 'ابن', 'member'),
('member.child_of_male', 'en', 'son of', 'member'),
-- spouse keys
('spouse.saved_locally', 'ar', 'تم حفظ البيانات محلياً', 'spouse'),
('spouse.saved_locally', 'en', 'Data saved locally', 'spouse'),
('spouse.saved_locally_desc', 'ar', 'تم حفظ بيانات الشريك محلياً', 'spouse'),
('spouse.saved_locally_desc', 'en', 'Spouse data saved locally', 'spouse'),
('spouse.save_error', 'ar', 'خطأ في الحفظ', 'spouse'),
('spouse.save_error', 'en', 'Save error', 'spouse'),
('spouse.save_error_desc', 'ar', 'حدث خطأ أثناء حفظ البيانات', 'spouse'),
('spouse.save_error_desc', 'en', 'An error occurred while saving data', 'spouse'),
('spouse.deleted', 'ar', 'تم الحذف', 'spouse'),
('spouse.deleted', 'en', 'Deleted', 'spouse'),
('spouse.deleted_desc', 'ar', 'سيتم تأكيد الحذف عند حفظ العضو', 'spouse'),
('spouse.deleted_desc', 'en', 'Deletion will be confirmed when saving the member', 'spouse'),
-- common keys
('common.edit', 'ar', 'تعديل', 'common'),
('common.edit', 'en', 'Edit', 'common'),
('common.no', 'ar', 'لا', 'common'),
('common.no', 'en', 'No', 'common'),
-- upgrade keys
('upgrade.feature_locked', 'ar', 'ميزة مدفوعة', 'upgrade'),
('upgrade.feature_locked', 'en', 'Premium Feature', 'upgrade'),
('upgrade.upgrade_now', 'ar', 'ترقية الآن', 'upgrade'),
('upgrade.upgrade_now', 'en', 'Upgrade Now', 'upgrade'),
-- stitch keys
('stitch.add_new_member', 'ar', 'إضافة عضو جديد', 'stitch'),
('stitch.add_new_member', 'en', 'Add New Member', 'stitch'),
('stitch.add_member_desc', 'ar', 'أنشئ ملفاً شخصياً جديداً لعضو في شجرة العائلة', 'stitch'),
('stitch.add_member_desc', 'en', 'Create a new profile for a family member in the family tree', 'stitch')
ON CONFLICT (key, language_code) DO UPDATE SET value = EXCLUDED.value, category = EXCLUDED.category, updated_at = now();
