
INSERT INTO translations (key, language_code, value, category) VALUES
('gallery.load_error', 'ar', 'فشل تحميل المعرض', 'gallery'),
('gallery.load_error', 'en', 'Failed to load gallery', 'gallery'),
('gallery.filter_members', 'ar', 'الفلتر والأعضاء', 'gallery'),
('gallery.filter_members', 'en', 'Filter & Members', 'gallery'),
('gallery.upgrade_now', 'ar', 'ترقية الآن', 'gallery'),
('gallery.upgrade_now', 'en', 'Upgrade Now', 'gallery'),
('gallery.storage_capacity', 'ar', 'سعة التخزين', 'gallery'),
('gallery.storage_capacity', 'en', 'Storage Capacity', 'gallery'),
('gallery.locked', 'ar', 'مقفل', 'gallery'),
('gallery.locked', 'en', 'LOCKED', 'gallery'),
('gallery.premium_storage', 'ar', 'الباقة المميزة مطلوبة لتخزين الوسائط', 'gallery'),
('gallery.premium_storage', 'en', 'Premium plan required for media storage', 'gallery'),
('gallery.filter_disabled', 'ar', 'الفلتر معطل...', 'gallery'),
('gallery.filter_disabled', 'en', 'Filter disabled...', 'gallery'),
('gallery.filter_member', 'ar', 'البحث بأسماء الأعضاء...', 'gallery'),
('gallery.filter_member', 'en', 'Filter by family member...', 'gallery'),
('gallery.all_photos', 'ar', 'كل الصور', 'gallery'),
('gallery.all_photos', 'en', 'All Photos', 'gallery'),
('gallery.memories', 'ar', 'ذكريات', 'gallery'),
('gallery.memories', 'en', 'Memories', 'gallery'),
('gallery.subtitle', 'ar', 'لحظات عائلية ثمينة عبر الأجيال', 'gallery'),
('gallery.subtitle', 'en', 'Precious family moments across generations', 'gallery'),
('gallery.total_items', 'ar', 'إجمالي العناصر', 'gallery'),
('gallery.total_items', 'en', 'Total Items', 'gallery'),
('gallery.empty_title', 'ar', 'معرض صور العائلة فارغ', 'gallery'),
('gallery.empty_title', 'en', 'Your Family Gallery is Empty', 'gallery'),
('gallery.empty_description', 'ar', 'ابدأ بتوثيق إرثك العائلي برفع أول ذكرى.', 'gallery'),
('gallery.empty_description', 'en', 'Start preserving your legacy by uploading your first memory.', 'gallery'),
('gallery.family_history', 'ar', 'تاريخ العائلة', 'gallery'),
('gallery.family_history', 'en', 'Family History', 'gallery'),
('gallery.captured_on', 'ar', 'تاريخ الالتقاط', 'gallery'),
('gallery.captured_on', 'en', 'Captured On', 'gallery'),
('gallery.uploaded_at', 'ar', 'تاريخ الرفع', 'gallery'),
('gallery.uploaded_at', 'en', 'Uploaded', 'gallery'),
('gallery.tagged_members', 'ar', 'الأشخاص المحددون', 'gallery'),
('gallery.tagged_members', 'en', 'Tagged Members', 'gallery'),
('gallery.tags', 'ar', 'الوسوم', 'gallery'),
('gallery.tags', 'en', 'Tags', 'gallery'),
('gallery.download', 'ar', 'تحميل', 'gallery'),
('gallery.download', 'en', 'Download', 'gallery'),
('gallery.edit_details', 'ar', 'تعديل التفاصيل', 'gallery'),
('gallery.edit_details', 'en', 'Edit Details', 'gallery'),
('gallery.delete_permanently', 'ar', 'حذف نهائي', 'gallery'),
('gallery.delete_permanently', 'en', 'Delete Permanently', 'gallery'),
('gallery.review_details', 'ar', 'مراجعة تفاصيل الذكرى', 'gallery'),
('gallery.review_details', 'en', 'Review Memory Details', 'gallery'),
('gallery.edit_memory', 'ar', 'تعديل تفاصيل الذكرى', 'gallery'),
('gallery.edit_memory', 'en', 'Edit Memory Details', 'gallery'),
('gallery.search_member', 'ar', 'ابحث عن عضو...', 'gallery'),
('gallery.search_member', 'en', 'Search for a member...', 'gallery'),
('gallery.no_members_available', 'ar', 'لا يوجد أعضاء متاحين', 'gallery'),
('gallery.no_members_available', 'en', 'No members available', 'gallery'),
('gallery.click_to_tag', 'ar', 'اضغط على الصورة لتحديد الأشخاص', 'gallery'),
('gallery.click_to_tag', 'en', 'Click on the image to tag members', 'gallery'),
('gallery.description_label', 'ar', 'الوصف', 'gallery'),
('gallery.description_label', 'en', 'Description', 'gallery'),
('gallery.description_placeholder', 'ar', 'احكِ قصة هذه الصورة... من فيها؟ ماذا حدث في ذلك اليوم؟', 'gallery'),
('gallery.description_placeholder', 'en', 'Tell the story behind this photo... Who is in it? What happened that day?', 'gallery'),
('gallery.tagged', 'ar', 'المحددون', 'gallery'),
('gallery.tagged', 'en', 'Tagged', 'gallery'),
('gallery.add_member', 'ar', 'إضافة عضو...', 'gallery'),
('gallery.add_member', 'en', 'Add member...', 'gallery'),
('gallery.no_members_found', 'ar', 'لم يتم العثور على أعضاء', 'gallery'),
('gallery.no_members_found', 'en', 'No members found', 'gallery'),
('gallery.no_tags_yet', 'ar', 'اضغط على الصورة لتحديد الأعضاء', 'gallery'),
('gallery.no_tags_yet', 'en', 'Click on the image to tag members', 'gallery'),
('gallery.date_of_event', 'ar', 'تاريخ الحدث', 'gallery'),
('gallery.date_of_event', 'en', 'Date of Event', 'gallery'),
('gallery.discard', 'ar', 'تجاهل', 'gallery'),
('gallery.discard', 'en', 'Discard', 'gallery'),
('gallery.upload_to_gallery', 'ar', 'رفع إلى المعرض', 'gallery'),
('gallery.upload_to_gallery', 'en', 'Upload to Gallery', 'gallery'),
('gallery.save_changes', 'ar', 'حفظ التغييرات', 'gallery'),
('gallery.save_changes', 'en', 'Save Changes', 'gallery'),
('gallery.upload_error', 'ar', 'فشل رفع الصور', 'gallery'),
('gallery.upload_error', 'en', 'Failed to upload photos', 'gallery'),
('gallery.update_success', 'ar', 'تم تحديث الذكرى بنجاح', 'gallery'),
('gallery.update_success', 'en', 'Memory updated successfully', 'gallery'),
('gallery.save_error', 'ar', 'فشل الحفظ', 'gallery'),
('gallery.save_error', 'en', 'Failed to save', 'gallery'),
('gallery.delete_error', 'ar', 'فشل حذف الصورة', 'gallery'),
('gallery.delete_error', 'en', 'Failed to delete photo', 'gallery'),
('gallery.memory_preview', 'ar', 'معاينة الذكرى', 'gallery'),
('gallery.memory_preview', 'en', 'Memory Preview', 'gallery')
ON CONFLICT (key, language_code) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
